linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - revive
    - unused
    - misspell

run:
  timeout: 5m
  go: '1.25'

linters-settings:
  revive:
    rules:
      - name: exported
        disabled: true

issues:
  exclude-rules:
    - path: '_test\.go'
      linters:
        - errcheck
        - revive
    - text: 'Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|.*Write).* is not checked'
      linters:
        - errcheck
