// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: budget.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCampaignBudget = `-- name: GetCampaignBudget :one

SELECT 
    c.id, c.customer_id, c.budget_limit, c.current_spend, c.status,
    cust.balance as customer_balance
FROM campaigns c
JOIN customers cust ON c.customer_id = cust.id
WHERE c.id = $1 LIMIT 1
`

type GetCampaignBudgetRow struct {
	ID              pgtype.UUID        `json:"id"`
	CustomerID      pgtype.UUID        `json:"customer_id"`
	BudgetLimit     int64              `json:"budget_limit"`
	CurrentSpend    int64              `json:"current_spend"`
	Status          CampaignStatusType `json:"status"`
	CustomerBalance int64              `json:"customer_balance"`
}

// budget.sql: sqlc query definitions for budget and customer balance management.
// UpdateCampaignSpend uses an inline CASE to atomically set status to EXHAUSTED
// when current_spend + delta >= budget_limit, eliminating a separate UPDATE round-trip.
// UpdateCustomerBalance is a simple decrement; the corresponding spend is tracked
// in the campaign record. Both queries are executed inside a PostgreSQL transaction
// with an idempotency check (sync_idempotency) by CampaignRepo and CustomerRepo.
func (q *Queries) GetCampaignBudget(ctx context.Context, id pgtype.UUID) (GetCampaignBudgetRow, error) {
	row := q.db.QueryRow(ctx, getCampaignBudget, id)
	var i GetCampaignBudgetRow
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.BudgetLimit,
		&i.CurrentSpend,
		&i.Status,
		&i.CustomerBalance,
	)
	return i, err
}

const getCustomerByID = `-- name: GetCustomerByID :one
SELECT id, name, balance, currency, created_at, updated_at, allowed_overdraft FROM customers WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCustomerByID(ctx context.Context, id pgtype.UUID) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByID, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AllowedOverdraft,
	)
	return i, err
}

const listActiveCampaigns = `-- name: ListActiveCampaigns :many
SELECT id, name, status, budget_limit, created_at, updated_at, customer_id, current_spend, deleted_at, pacing_mode, daily_budget, timezone, freq_limit, freq_window, target_countries, brand_id, brand_fcap_key FROM campaigns WHERE status = 'ACTIVE'
`

func (q *Queries) ListActiveCampaigns(ctx context.Context) ([]Campaign, error) {
	rows, err := q.db.Query(ctx, listActiveCampaigns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Campaign
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.BudgetLimit,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CustomerID,
			&i.CurrentSpend,
			&i.DeletedAt,
			&i.PacingMode,
			&i.DailyBudget,
			&i.Timezone,
			&i.FreqLimit,
			&i.FreqWindow,
			&i.TargetCountries,
			&i.BrandID,
			&i.BrandFcapKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCampaignSpend = `-- name: UpdateCampaignSpend :exec
UPDATE campaigns 
SET current_spend = current_spend + $2,
    status = CASE 
        WHEN current_spend + $2 >= budget_limit THEN 'EXHAUSTED'::campaign_status_type 
        ELSE status 
    END,
    updated_at = NOW()
WHERE id = $1
`

type UpdateCampaignSpendParams struct {
	ID           pgtype.UUID `json:"id"`
	CurrentSpend int64       `json:"current_spend"`
}

func (q *Queries) UpdateCampaignSpend(ctx context.Context, arg UpdateCampaignSpendParams) error {
	_, err := q.db.Exec(ctx, updateCampaignSpend, arg.ID, arg.CurrentSpend)
	return err
}

const updateCustomerBalance = `-- name: UpdateCustomerBalance :exec
UPDATE customers 
SET balance = balance - $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateCustomerBalanceParams struct {
	ID      pgtype.UUID `json:"id"`
	Balance int64       `json:"balance"`
}

func (q *Queries) UpdateCustomerBalance(ctx context.Context, arg UpdateCustomerBalanceParams) error {
	_, err := q.db.Exec(ctx, updateCustomerBalance, arg.ID, arg.Balance)
	return err
}
