// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: management.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupAuditLogs = `-- name: CleanupAuditLogs :exec
DELETE FROM admin_audit_log
WHERE created_at < $1
`

func (q *Queries) CleanupAuditLogs(ctx context.Context, createdAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, cleanupAuditLogs, createdAt)
	return err
}

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO admin_audit_log (admin_id, action, target_type, target_id, changes, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, admin_id, action, target_type, target_id, changes, metadata, created_at
`

type CreateAuditLogParams struct {
	AdminID    pgtype.UUID `json:"admin_id"`
	Action     string      `json:"action"`
	TargetType string      `json:"target_type"`
	TargetID   pgtype.UUID `json:"target_id"`
	Changes    []byte      `json:"changes"`
	Metadata   []byte      `json:"metadata"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AdminAuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.AdminID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Changes,
		arg.Metadata,
	)
	var i AdminAuditLog
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.Action,
		&i.TargetType,
		&i.TargetID,
		&i.Changes,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (id, name, balance, currency)
VALUES ($1, $2, $3, $4)
RETURNING id, name, balance, currency, created_at, updated_at
`

type CreateCustomerParams struct {
	ID       pgtype.UUID    `json:"id"`
	Name     string         `json:"name"`
	Balance  pgtype.Numeric `json:"balance"`
	Currency string         `json:"currency"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer,
		arg.ID,
		arg.Name,
		arg.Balance,
		arg.Currency,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createLedgerEntry = `-- name: CreateLedgerEntry :one
INSERT INTO balance_ledger (customer_id, campaign_id, amount, type, idempotency_hash)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, customer_id, campaign_id, amount, type, idempotency_hash, created_at
`

type CreateLedgerEntryParams struct {
	CustomerID      pgtype.UUID    `json:"customer_id"`
	CampaignID      pgtype.UUID    `json:"campaign_id"`
	Amount          pgtype.Numeric `json:"amount"`
	Type            LedgerType     `json:"type"`
	IdempotencyHash pgtype.Text    `json:"idempotency_hash"`
}

func (q *Queries) CreateLedgerEntry(ctx context.Context, arg CreateLedgerEntryParams) (BalanceLedger, error) {
	row := q.db.QueryRow(ctx, createLedgerEntry,
		arg.CustomerID,
		arg.CampaignID,
		arg.Amount,
		arg.Type,
		arg.IdempotencyHash,
	)
	var i BalanceLedger
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.CampaignID,
		&i.Amount,
		&i.Type,
		&i.IdempotencyHash,
		&i.CreatedAt,
	)
	return i, err
}

const createStatusHistory = `-- name: CreateStatusHistory :exec
INSERT INTO campaign_status_history (campaign_id, old_status, new_status, reason)
VALUES ($1, $2, $3, $4)
`

type CreateStatusHistoryParams struct {
	CampaignID pgtype.UUID            `json:"campaign_id"`
	OldStatus  NullCampaignStatusType `json:"old_status"`
	NewStatus  CampaignStatusType     `json:"new_status"`
	Reason     pgtype.Text            `json:"reason"`
}

func (q *Queries) CreateStatusHistory(ctx context.Context, arg CreateStatusHistoryParams) error {
	_, err := q.db.Exec(ctx, createStatusHistory,
		arg.CampaignID,
		arg.OldStatus,
		arg.NewStatus,
		arg.Reason,
	)
	return err
}

const getCampaignFull = `-- name: GetCampaignFull :one
SELECT id, name, status, budget_limit, created_at, updated_at, customer_id, current_spend, deleted_at FROM campaigns
WHERE id = $1
`

func (q *Queries) GetCampaignFull(ctx context.Context, id pgtype.UUID) (Campaign, error) {
	row := q.db.QueryRow(ctx, getCampaignFull, id)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.BudgetLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomerID,
		&i.CurrentSpend,
		&i.DeletedAt,
	)
	return i, err
}

const getCustomerForUpdate = `-- name: GetCustomerForUpdate :one
SELECT id, name, balance, currency, created_at, updated_at FROM customers
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetCustomerForUpdate(ctx context.Context, id pgtype.UUID) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerForUpdate, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLedgerByHash = `-- name: GetLedgerByHash :one
SELECT id, customer_id, campaign_id, amount, type, idempotency_hash, created_at FROM balance_ledger
WHERE idempotency_hash = $1
`

func (q *Queries) GetLedgerByHash(ctx context.Context, idempotencyHash pgtype.Text) (BalanceLedger, error) {
	row := q.db.QueryRow(ctx, getLedgerByHash, idempotencyHash)
	var i BalanceLedger
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.CampaignID,
		&i.Amount,
		&i.Type,
		&i.IdempotencyHash,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, admin_id, action, target_type, target_id, changes, metadata, created_at FROM admin_audit_log
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAuditLogsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AdminAuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminAuditLog
	for rows.Next() {
		var i AdminAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.AdminID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Changes,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCampaign = `-- name: SoftDeleteCampaign :exec
UPDATE campaigns
SET status = 'DELETED',
    deleted_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) SoftDeleteCampaign(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteCampaign, id)
	return err
}

const updateCampaignStatus = `-- name: UpdateCampaignStatus :one
UPDATE campaigns
SET status = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, status, budget_limit, created_at, updated_at, customer_id, current_spend, deleted_at
`

type UpdateCampaignStatusParams struct {
	ID     pgtype.UUID        `json:"id"`
	Status CampaignStatusType `json:"status"`
}

func (q *Queries) UpdateCampaignStatus(ctx context.Context, arg UpdateCampaignStatusParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, updateCampaignStatus, arg.ID, arg.Status)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.BudgetLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomerID,
		&i.CurrentSpend,
		&i.DeletedAt,
	)
	return i, err
}

const updateCustomerBalanceManagement = `-- name: UpdateCustomerBalanceManagement :one
UPDATE customers
SET balance = balance + $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, balance, currency, created_at, updated_at
`

type UpdateCustomerBalanceManagementParams struct {
	ID      pgtype.UUID    `json:"id"`
	Balance pgtype.Numeric `json:"balance"`
}

func (q *Queries) UpdateCustomerBalanceManagement(ctx context.Context, arg UpdateCustomerBalanceManagementParams) (Customer, error) {
	row := q.db.QueryRow(ctx, updateCustomerBalanceManagement, arg.ID, arg.Balance)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
