// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type CampaignStatusType string

const (
	CampaignStatusTypeACTIVE    CampaignStatusType = "ACTIVE"
	CampaignStatusTypePAUSED    CampaignStatusType = "PAUSED"
	CampaignStatusTypeEXHAUSTED CampaignStatusType = "EXHAUSTED"
	CampaignStatusTypeDRAINING  CampaignStatusType = "DRAINING"
	CampaignStatusTypeDELETED   CampaignStatusType = "DELETED"
)

func (e *CampaignStatusType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CampaignStatusType(s)
	case string:
		*e = CampaignStatusType(s)
	default:
		return fmt.Errorf("unsupported scan type for CampaignStatusType: %T", src)
	}
	return nil
}

type NullCampaignStatusType struct {
	CampaignStatusType CampaignStatusType `json:"campaign_status_type"`
	Valid              bool               `json:"valid"` // Valid is true if CampaignStatusType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCampaignStatusType) Scan(value interface{}) error {
	if value == nil {
		ns.CampaignStatusType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CampaignStatusType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCampaignStatusType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CampaignStatusType), nil
}

type LedgerType string

const (
	LedgerTypeTOPUP   LedgerType = "TOPUP"
	LedgerTypeFREEZE  LedgerType = "FREEZE"
	LedgerTypeRELEASE LedgerType = "RELEASE"
	LedgerTypeFEE     LedgerType = "FEE"
	LedgerTypeREFUND  LedgerType = "REFUND"
)

func (e *LedgerType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LedgerType(s)
	case string:
		*e = LedgerType(s)
	default:
		return fmt.Errorf("unsupported scan type for LedgerType: %T", src)
	}
	return nil
}

type NullLedgerType struct {
	LedgerType LedgerType `json:"ledger_type"`
	Valid      bool       `json:"valid"` // Valid is true if LedgerType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLedgerType) Scan(value interface{}) error {
	if value == nil {
		ns.LedgerType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LedgerType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLedgerType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LedgerType), nil
}

type PacingModeType string

const (
	PacingModeTypeASAP PacingModeType = "ASAP"
	PacingModeTypeEVEN PacingModeType = "EVEN"
)

func (e *PacingModeType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PacingModeType(s)
	case string:
		*e = PacingModeType(s)
	default:
		return fmt.Errorf("unsupported scan type for PacingModeType: %T", src)
	}
	return nil
}

type NullPacingModeType struct {
	PacingModeType PacingModeType `json:"pacing_mode_type"`
	Valid          bool           `json:"valid"` // Valid is true if PacingModeType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPacingModeType) Scan(value interface{}) error {
	if value == nil {
		ns.PacingModeType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PacingModeType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPacingModeType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PacingModeType), nil
}

type AdminAuditLog struct {
	ID         int64              `json:"id"`
	AdminID    pgtype.UUID        `json:"admin_id"`
	Action     string             `json:"action"`
	TargetType string             `json:"target_type"`
	TargetID   pgtype.UUID        `json:"target_id"`
	Changes    []byte             `json:"changes"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type AdvertiserBrand struct {
	ID         pgtype.UUID        `json:"id"`
	CustomerID pgtype.UUID        `json:"customer_id"`
	Name       string             `json:"name"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	FreqLimit  int32              `json:"freq_limit"`
	FreqWindow int32              `json:"freq_window"`
}

type BalanceLedger struct {
	ID              int64            `json:"id"`
	CustomerID      pgtype.UUID      `json:"customer_id"`
	CampaignID      pgtype.UUID      `json:"campaign_id"`
	Amount          int64            `json:"amount"`
	Type            LedgerType       `json:"type"`
	IdempotencyHash pgtype.Text      `json:"idempotency_hash"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
}

type Campaign struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Status       CampaignStatusType `json:"status"`
	BudgetLimit  int64              `json:"budget_limit"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	CustomerID   pgtype.UUID        `json:"customer_id"`
	CurrentSpend int64              `json:"current_spend"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	PacingMode   PacingModeType     `json:"pacing_mode"`
	DailyBudget  int64              `json:"daily_budget"`
	Timezone     string             `json:"timezone"`
	// Max events per user. 0 means unlimited.
	FreqLimit pgtype.Int4 `json:"freq_limit"`
	// Time window for frequency capping in seconds.
	FreqWindow pgtype.Int4 `json:"freq_window"`
	// Array of allowed ISO country codes. NULL or empty means all countries allowed.
	TargetCountries []string    `json:"target_countries"`
	BrandID         pgtype.UUID `json:"brand_id"`
	BrandFcapKey    string      `json:"brand_fcap_key"`
}

type CampaignStat struct {
	CampaignID       pgtype.UUID `json:"campaign_id"`
	Date             pgtype.Date `json:"date"`
	ImpressionsCount int64       `json:"impressions_count"`
	ClicksCount      int64       `json:"clicks_count"`
	ConversionsCount int64       `json:"conversions_count"`
}

type CampaignStatusHistory struct {
	ID         int64                  `json:"id"`
	CampaignID pgtype.UUID            `json:"campaign_id"`
	OldStatus  NullCampaignStatusType `json:"old_status"`
	NewStatus  CampaignStatusType     `json:"new_status"`
	Reason     pgtype.Text            `json:"reason"`
	CreatedAt  pgtype.Timestamp       `json:"created_at"`
}

type Customer struct {
	ID               pgtype.UUID        `json:"id"`
	Name             string             `json:"name"`
	Balance          int64              `json:"balance"`
	Currency         string             `json:"currency"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	AllowedOverdraft int64              `json:"allowed_overdraft"`
}

type Event struct {
	ClickID     string             `json:"click_id"`
	CampaignID  pgtype.UUID        `json:"campaign_id"`
	EventType   string             `json:"event_type"`
	Payload     []byte             `json:"payload"`
	IpAddress   pgtype.Text        `json:"ip_address"`
	UserAgent   pgtype.Text        `json:"user_agent"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedDate pgtype.Date        `json:"created_date"`
	UserID      pgtype.Text        `json:"user_id"`
}

type EventsDefault struct {
	ClickID     string             `json:"click_id"`
	CampaignID  pgtype.UUID        `json:"campaign_id"`
	EventType   string             `json:"event_type"`
	Payload     []byte             `json:"payload"`
	IpAddress   pgtype.Text        `json:"ip_address"`
	UserAgent   pgtype.Text        `json:"user_agent"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedDate pgtype.Date        `json:"created_date"`
}

type IpBlacklist struct {
	ID        int64              `json:"id"`
	Ip        string             `json:"ip"`
	Reason    string             `json:"reason"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type OutboxEvent struct {
	ID        int64              `json:"id"`
	EventType string             `json:"event_type"`
	Payload   []byte             `json:"payload"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type SyncIdempotency struct {
	ID        string             `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type SystemSetting struct {
	Key       string             `json:"key"`
	Value     string             `json:"value"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
