apiVersion: v1
kind: Service
metadata:
  name: billing
  namespace: espx
  labels:
    app.kubernetes.io/name: billing
    app.kubernetes.io/part-of: espx
spec:
  selector:
    app.kubernetes.io/name: billing
  ports:
    - name: grpc
      port: 51054
      targetPort: grpc
