apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: espx
  labels:
    app.kubernetes.io/name: payment
    app.kubernetes.io/part-of: espx
spec:
  selector:
    app.kubernetes.io/name: payment
  ports:
    - name: grpc
      port: 51052
      targetPort: grpc
    - name: webhook
      port: 8187
      targetPort: webhook
