// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: settlement.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApplyPaymentCreditRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	CustomerId           string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	AmountMicro          int64                  `protobuf:"varint,2,opt,name=amount_micro,json=amountMicro,proto3" json:"amount_micro,omitempty"`
	LedgerIdempotencyKey string                 `protobuf:"bytes,3,opt,name=ledger_idempotency_key,json=ledgerIdempotencyKey,proto3" json:"ledger_idempotency_key,omitempty"` // e.g. "stripe:evt_01H..."
	PaymentIntentId      string                 `protobuf:"bytes,4,opt,name=payment_intent_id,json=paymentIntentId,proto3" json:"payment_intent_id,omitempty"`
	Provider             string                 `protobuf:"bytes,5,opt,name=provider,proto3" json:"provider,omitempty"`
	ProviderRef          string                 `protobuf:"bytes,6,opt,name=provider_ref,json=providerRef,proto3" json:"provider_ref,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ApplyPaymentCreditRequest) Reset() {
	*x = ApplyPaymentCreditRequest{}
	mi := &file_settlement_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyPaymentCreditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyPaymentCreditRequest) ProtoMessage() {}

func (x *ApplyPaymentCreditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_settlement_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyPaymentCreditRequest.ProtoReflect.Descriptor instead.
func (*ApplyPaymentCreditRequest) Descriptor() ([]byte, []int) {
	return file_settlement_proto_rawDescGZIP(), []int{0}
}

func (x *ApplyPaymentCreditRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *ApplyPaymentCreditRequest) GetAmountMicro() int64 {
	if x != nil {
		return x.AmountMicro
	}
	return 0
}

func (x *ApplyPaymentCreditRequest) GetLedgerIdempotencyKey() string {
	if x != nil {
		return x.LedgerIdempotencyKey
	}
	return ""
}

func (x *ApplyPaymentCreditRequest) GetPaymentIntentId() string {
	if x != nil {
		return x.PaymentIntentId
	}
	return ""
}

func (x *ApplyPaymentCreditRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ApplyPaymentCreditRequest) GetProviderRef() string {
	if x != nil {
		return x.ProviderRef
	}
	return ""
}

type ApplyPaymentCreditResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Applied       bool                   `protobuf:"varint,1,opt,name=applied,proto3" json:"applied,omitempty"` // false = duplicate idempotency hit (still success)
	LedgerEntryId int64                  `protobuf:"varint,2,opt,name=ledger_entry_id,json=ledgerEntryId,proto3" json:"ledger_entry_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyPaymentCreditResponse) Reset() {
	*x = ApplyPaymentCreditResponse{}
	mi := &file_settlement_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyPaymentCreditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyPaymentCreditResponse) ProtoMessage() {}

func (x *ApplyPaymentCreditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_settlement_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyPaymentCreditResponse.ProtoReflect.Descriptor instead.
func (*ApplyPaymentCreditResponse) Descriptor() ([]byte, []int) {
	return file_settlement_proto_rawDescGZIP(), []int{1}
}

func (x *ApplyPaymentCreditResponse) GetApplied() bool {
	if x != nil {
		return x.Applied
	}
	return false
}

func (x *ApplyPaymentCreditResponse) GetLedgerEntryId() int64 {
	if x != nil {
		return x.LedgerEntryId
	}
	return 0
}

type ApplyPaymentRefundRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	CustomerId           string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	AmountMicro          int64                  `protobuf:"varint,2,opt,name=amount_micro,json=amountMicro,proto3" json:"amount_micro,omitempty"`                             // positive debit magnitude
	LedgerIdempotencyKey string                 `protobuf:"bytes,3,opt,name=ledger_idempotency_key,json=ledgerIdempotencyKey,proto3" json:"ledger_idempotency_key,omitempty"` // e.g. "refund:re_01H..."
	PaymentIntentId      string                 `protobuf:"bytes,4,opt,name=payment_intent_id,json=paymentIntentId,proto3" json:"payment_intent_id,omitempty"`
	Provider             string                 `protobuf:"bytes,5,opt,name=provider,proto3" json:"provider,omitempty"`
	ProviderRefundId     string                 `protobuf:"bytes,6,opt,name=provider_refund_id,json=providerRefundId,proto3" json:"provider_refund_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ApplyPaymentRefundRequest) Reset() {
	*x = ApplyPaymentRefundRequest{}
	mi := &file_settlement_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyPaymentRefundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyPaymentRefundRequest) ProtoMessage() {}

func (x *ApplyPaymentRefundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_settlement_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyPaymentRefundRequest.ProtoReflect.Descriptor instead.
func (*ApplyPaymentRefundRequest) Descriptor() ([]byte, []int) {
	return file_settlement_proto_rawDescGZIP(), []int{2}
}

func (x *ApplyPaymentRefundRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *ApplyPaymentRefundRequest) GetAmountMicro() int64 {
	if x != nil {
		return x.AmountMicro
	}
	return 0
}

func (x *ApplyPaymentRefundRequest) GetLedgerIdempotencyKey() string {
	if x != nil {
		return x.LedgerIdempotencyKey
	}
	return ""
}

func (x *ApplyPaymentRefundRequest) GetPaymentIntentId() string {
	if x != nil {
		return x.PaymentIntentId
	}
	return ""
}

func (x *ApplyPaymentRefundRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ApplyPaymentRefundRequest) GetProviderRefundId() string {
	if x != nil {
		return x.ProviderRefundId
	}
	return ""
}

type ApplyPaymentRefundResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Applied       bool                   `protobuf:"varint,1,opt,name=applied,proto3" json:"applied,omitempty"`
	LedgerEntryId int64                  `protobuf:"varint,2,opt,name=ledger_entry_id,json=ledgerEntryId,proto3" json:"ledger_entry_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyPaymentRefundResponse) Reset() {
	*x = ApplyPaymentRefundResponse{}
	mi := &file_settlement_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyPaymentRefundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyPaymentRefundResponse) ProtoMessage() {}

func (x *ApplyPaymentRefundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_settlement_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyPaymentRefundResponse.ProtoReflect.Descriptor instead.
func (*ApplyPaymentRefundResponse) Descriptor() ([]byte, []int) {
	return file_settlement_proto_rawDescGZIP(), []int{3}
}

func (x *ApplyPaymentRefundResponse) GetApplied() bool {
	if x != nil {
		return x.Applied
	}
	return false
}

func (x *ApplyPaymentRefundResponse) GetLedgerEntryId() int64 {
	if x != nil {
		return x.LedgerEntryId
	}
	return 0
}

type ApplyPaymentChargebackRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	CustomerId           string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	AmountMicro          int64                  `protobuf:"varint,2,opt,name=amount_micro,json=amountMicro,proto3" json:"amount_micro,omitempty"`
	LedgerIdempotencyKey string                 `protobuf:"bytes,3,opt,name=ledger_idempotency_key,json=ledgerIdempotencyKey,proto3" json:"ledger_idempotency_key,omitempty"` // e.g. "chargeback:withdrawn:dp_01H..."
	PaymentIntentId      string                 `protobuf:"bytes,4,opt,name=payment_intent_id,json=paymentIntentId,proto3" json:"payment_intent_id,omitempty"`
	Provider             string                 `protobuf:"bytes,5,opt,name=provider,proto3" json:"provider,omitempty"`
	ProviderDisputeId    string                 `protobuf:"bytes,6,opt,name=provider_dispute_id,json=providerDisputeId,proto3" json:"provider_dispute_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ApplyPaymentChargebackRequest) Reset() {
	*x = ApplyPaymentChargebackRequest{}
	mi := &file_settlement_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyPaymentChargebackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyPaymentChargebackRequest) ProtoMessage() {}

func (x *ApplyPaymentChargebackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_settlement_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyPaymentChargebackRequest.ProtoReflect.Descriptor instead.
func (*ApplyPaymentChargebackRequest) Descriptor() ([]byte, []int) {
	return file_settlement_proto_rawDescGZIP(), []int{4}
}

func (x *ApplyPaymentChargebackRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *ApplyPaymentChargebackRequest) GetAmountMicro() int64 {
	if x != nil {
		return x.AmountMicro
	}
	return 0
}

func (x *ApplyPaymentChargebackRequest) GetLedgerIdempotencyKey() string {
	if x != nil {
		return x.LedgerIdempotencyKey
	}
	return ""
}

func (x *ApplyPaymentChargebackRequest) GetPaymentIntentId() string {
	if x != nil {
		return x.PaymentIntentId
	}
	return ""
}

func (x *ApplyPaymentChargebackRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ApplyPaymentChargebackRequest) GetProviderDisputeId() string {
	if x != nil {
		return x.ProviderDisputeId
	}
	return ""
}

type ApplyPaymentChargebackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Applied       bool                   `protobuf:"varint,1,opt,name=applied,proto3" json:"applied,omitempty"`
	LedgerEntryId int64                  `protobuf:"varint,2,opt,name=ledger_entry_id,json=ledgerEntryId,proto3" json:"ledger_entry_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyPaymentChargebackResponse) Reset() {
	*x = ApplyPaymentChargebackResponse{}
	mi := &file_settlement_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyPaymentChargebackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyPaymentChargebackResponse) ProtoMessage() {}

func (x *ApplyPaymentChargebackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_settlement_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyPaymentChargebackResponse.ProtoReflect.Descriptor instead.
func (*ApplyPaymentChargebackResponse) Descriptor() ([]byte, []int) {
	return file_settlement_proto_rawDescGZIP(), []int{5}
}

func (x *ApplyPaymentChargebackResponse) GetApplied() bool {
	if x != nil {
		return x.Applied
	}
	return false
}

func (x *ApplyPaymentChargebackResponse) GetLedgerEntryId() int64 {
	if x != nil {
		return x.LedgerEntryId
	}
	return 0
}

type ApplyPaymentChargebackReversalRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	CustomerId           string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	AmountMicro          int64                  `protobuf:"varint,2,opt,name=amount_micro,json=amountMicro,proto3" json:"amount_micro,omitempty"`
	LedgerIdempotencyKey string                 `protobuf:"bytes,3,opt,name=ledger_idempotency_key,json=ledgerIdempotencyKey,proto3" json:"ledger_idempotency_key,omitempty"` // e.g. "chargeback:reinstated:dp_01H..."
	PaymentIntentId      string                 `protobuf:"bytes,4,opt,name=payment_intent_id,json=paymentIntentId,proto3" json:"payment_intent_id,omitempty"`
	Provider             string                 `protobuf:"bytes,5,opt,name=provider,proto3" json:"provider,omitempty"`
	ProviderDisputeId    string                 `protobuf:"bytes,6,opt,name=provider_dispute_id,json=providerDisputeId,proto3" json:"provider_dispute_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ApplyPaymentChargebackReversalRequest) Reset() {
	*x = ApplyPaymentChargebackReversalRequest{}
	mi := &file_settlement_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyPaymentChargebackReversalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyPaymentChargebackReversalRequest) ProtoMessage() {}

func (x *ApplyPaymentChargebackReversalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_settlement_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyPaymentChargebackReversalRequest.ProtoReflect.Descriptor instead.
func (*ApplyPaymentChargebackReversalRequest) Descriptor() ([]byte, []int) {
	return file_settlement_proto_rawDescGZIP(), []int{6}
}

func (x *ApplyPaymentChargebackReversalRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *ApplyPaymentChargebackReversalRequest) GetAmountMicro() int64 {
	if x != nil {
		return x.AmountMicro
	}
	return 0
}

func (x *ApplyPaymentChargebackReversalRequest) GetLedgerIdempotencyKey() string {
	if x != nil {
		return x.LedgerIdempotencyKey
	}
	return ""
}

func (x *ApplyPaymentChargebackReversalRequest) GetPaymentIntentId() string {
	if x != nil {
		return x.PaymentIntentId
	}
	return ""
}

func (x *ApplyPaymentChargebackReversalRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ApplyPaymentChargebackReversalRequest) GetProviderDisputeId() string {
	if x != nil {
		return x.ProviderDisputeId
	}
	return ""
}

type ApplyPaymentChargebackReversalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Applied       bool                   `protobuf:"varint,1,opt,name=applied,proto3" json:"applied,omitempty"`
	LedgerEntryId int64                  `protobuf:"varint,2,opt,name=ledger_entry_id,json=ledgerEntryId,proto3" json:"ledger_entry_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyPaymentChargebackReversalResponse) Reset() {
	*x = ApplyPaymentChargebackReversalResponse{}
	mi := &file_settlement_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyPaymentChargebackReversalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyPaymentChargebackReversalResponse) ProtoMessage() {}

func (x *ApplyPaymentChargebackReversalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_settlement_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyPaymentChargebackReversalResponse.ProtoReflect.Descriptor instead.
func (*ApplyPaymentChargebackReversalResponse) Descriptor() ([]byte, []int) {
	return file_settlement_proto_rawDescGZIP(), []int{7}
}

func (x *ApplyPaymentChargebackReversalResponse) GetApplied() bool {
	if x != nil {
		return x.Applied
	}
	return false
}

func (x *ApplyPaymentChargebackReversalResponse) GetLedgerEntryId() int64 {
	if x != nil {
		return x.LedgerEntryId
	}
	return 0
}

type GetLedgerEntryRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PaymentIntentId string                 `protobuf:"bytes,1,opt,name=payment_intent_id,json=paymentIntentId,proto3" json:"payment_intent_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetLedgerEntryRequest) Reset() {
	*x = GetLedgerEntryRequest{}
	mi := &file_settlement_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLedgerEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLedgerEntryRequest) ProtoMessage() {}

func (x *GetLedgerEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_settlement_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLedgerEntryRequest.ProtoReflect.Descriptor instead.
func (*GetLedgerEntryRequest) Descriptor() ([]byte, []int) {
	return file_settlement_proto_rawDescGZIP(), []int{8}
}

func (x *GetLedgerEntryRequest) GetPaymentIntentId() string {
	if x != nil {
		return x.PaymentIntentId
	}
	return ""
}

type LedgerEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	CampaignId    string                 `protobuf:"bytes,3,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	AmountMicro   int64                  `protobuf:"varint,4,opt,name=amount_micro,json=amountMicro,proto3" json:"amount_micro,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedgerEntry) Reset() {
	*x = LedgerEntry{}
	mi := &file_settlement_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerEntry) ProtoMessage() {}

func (x *LedgerEntry) ProtoReflect() protoreflect.Message {
	mi := &file_settlement_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerEntry.ProtoReflect.Descriptor instead.
func (*LedgerEntry) Descriptor() ([]byte, []int) {
	return file_settlement_proto_rawDescGZIP(), []int{9}
}

func (x *LedgerEntry) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LedgerEntry) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *LedgerEntry) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *LedgerEntry) GetAmountMicro() int64 {
	if x != nil {
		return x.AmountMicro
	}
	return 0
}

func (x *LedgerEntry) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LedgerEntry) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetLedgerEntryResponse struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	Found                        bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Topup                        *LedgerEntry           `protobuf:"bytes,2,opt,name=topup,proto3" json:"topup,omitempty"`
	RefundTotalMicro             int64                  `protobuf:"varint,3,opt,name=refund_total_micro,json=refundTotalMicro,proto3" json:"refund_total_micro,omitempty"`
	ChargebackTotalMicro         int64                  `protobuf:"varint,4,opt,name=chargeback_total_micro,json=chargebackTotalMicro,proto3" json:"chargeback_total_micro,omitempty"`
	ChargebackReversalTotalMicro int64                  `protobuf:"varint,5,opt,name=chargeback_reversal_total_micro,json=chargebackReversalTotalMicro,proto3" json:"chargeback_reversal_total_micro,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *GetLedgerEntryResponse) Reset() {
	*x = GetLedgerEntryResponse{}
	mi := &file_settlement_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLedgerEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLedgerEntryResponse) ProtoMessage() {}

func (x *GetLedgerEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_settlement_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLedgerEntryResponse.ProtoReflect.Descriptor instead.
func (*GetLedgerEntryResponse) Descriptor() ([]byte, []int) {
	return file_settlement_proto_rawDescGZIP(), []int{10}
}

func (x *GetLedgerEntryResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetLedgerEntryResponse) GetTopup() *LedgerEntry {
	if x != nil {
		return x.Topup
	}
	return nil
}

func (x *GetLedgerEntryResponse) GetRefundTotalMicro() int64 {
	if x != nil {
		return x.RefundTotalMicro
	}
	return 0
}

func (x *GetLedgerEntryResponse) GetChargebackTotalMicro() int64 {
	if x != nil {
		return x.ChargebackTotalMicro
	}
	return 0
}

func (x *GetLedgerEntryResponse) GetChargebackReversalTotalMicro() int64 {
	if x != nil {
		return x.ChargebackReversalTotalMicro
	}
	return 0
}

var File_settlement_proto protoreflect.FileDescriptor

const file_settlement_proto_rawDesc = "" +
	"\n" +
	"\x10settlement.proto\x12\n" +
	"settlement\"\x80\x02\n" +
	"\x19ApplyPaymentCreditRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12!\n" +
	"\famount_micro\x18\x02 \x01(\x03R\vamountMicro\x124\n" +
	"\x16ledger_idempotency_key\x18\x03 \x01(\tR\x14ledgerIdempotencyKey\x12*\n" +
	"\x11payment_intent_id\x18\x04 \x01(\tR\x0fpaymentIntentId\x12\x1a\n" +
	"\bprovider\x18\x05 \x01(\tR\bprovider\x12!\n" +
	"\fprovider_ref\x18\x06 \x01(\tR\vproviderRef\"^\n" +
	"\x1aApplyPaymentCreditResponse\x12\x18\n" +
	"\aapplied\x18\x01 \x01(\bR\aapplied\x12&\n" +
	"\x0fledger_entry_id\x18\x02 \x01(\x03R\rledgerEntryId\"\x8b\x02\n" +
	"\x19ApplyPaymentRefundRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12!\n" +
	"\famount_micro\x18\x02 \x01(\x03R\vamountMicro\x124\n" +
	"\x16ledger_idempotency_key\x18\x03 \x01(\tR\x14ledgerIdempotencyKey\x12*\n" +
	"\x11payment_intent_id\x18\x04 \x01(\tR\x0fpaymentIntentId\x12\x1a\n" +
	"\bprovider\x18\x05 \x01(\tR\bprovider\x12,\n" +
	"\x12provider_refund_id\x18\x06 \x01(\tR\x10providerRefundId\"^\n" +
	"\x1aApplyPaymentRefundResponse\x12\x18\n" +
	"\aapplied\x18\x01 \x01(\bR\aapplied\x12&\n" +
	"\x0fledger_entry_id\x18\x02 \x01(\x03R\rledgerEntryId\"\x91\x02\n" +
	"\x1dApplyPaymentChargebackRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12!\n" +
	"\famount_micro\x18\x02 \x01(\x03R\vamountMicro\x124\n" +
	"\x16ledger_idempotency_key\x18\x03 \x01(\tR\x14ledgerIdempotencyKey\x12*\n" +
	"\x11payment_intent_id\x18\x04 \x01(\tR\x0fpaymentIntentId\x12\x1a\n" +
	"\bprovider\x18\x05 \x01(\tR\bprovider\x12.\n" +
	"\x13provider_dispute_id\x18\x06 \x01(\tR\x11providerDisputeId\"b\n" +
	"\x1eApplyPaymentChargebackResponse\x12\x18\n" +
	"\aapplied\x18\x01 \x01(\bR\aapplied\x12&\n" +
	"\x0fledger_entry_id\x18\x02 \x01(\x03R\rledgerEntryId\"\x99\x02\n" +
	"%ApplyPaymentChargebackReversalRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12!\n" +
	"\famount_micro\x18\x02 \x01(\x03R\vamountMicro\x124\n" +
	"\x16ledger_idempotency_key\x18\x03 \x01(\tR\x14ledgerIdempotencyKey\x12*\n" +
	"\x11payment_intent_id\x18\x04 \x01(\tR\x0fpaymentIntentId\x12\x1a\n" +
	"\bprovider\x18\x05 \x01(\tR\bprovider\x12.\n" +
	"\x13provider_dispute_id\x18\x06 \x01(\tR\x11providerDisputeId\"j\n" +
	"&ApplyPaymentChargebackReversalResponse\x12\x18\n" +
	"\aapplied\x18\x01 \x01(\bR\aapplied\x12&\n" +
	"\x0fledger_entry_id\x18\x02 \x01(\x03R\rledgerEntryId\"C\n" +
	"\x15GetLedgerEntryRequest\x12*\n" +
	"\x11payment_intent_id\x18\x01 \x01(\tR\x0fpaymentIntentId\"\xb5\x01\n" +
	"\vLedgerEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12\x1f\n" +
	"\vcampaign_id\x18\x03 \x01(\tR\n" +
	"campaignId\x12!\n" +
	"\famount_micro\x18\x04 \x01(\x03R\vamountMicro\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\"\x88\x02\n" +
	"\x16GetLedgerEntryResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12-\n" +
	"\x05topup\x18\x02 \x01(\v2\x17.settlement.LedgerEntryR\x05topup\x12,\n" +
	"\x12refund_total_micro\x18\x03 \x01(\x03R\x10refundTotalMicro\x124\n" +
	"\x16chargeback_total_micro\x18\x04 \x01(\x03R\x14chargebackTotalMicro\x12E\n" +
	"\x1fchargeback_reversal_total_micro\x18\x05 \x01(\x03R\x1cchargebackReversalTotalMicro2\xb1\x04\n" +
	"\x11SettlementService\x12c\n" +
	"\x12ApplyPaymentCredit\x12%.settlement.ApplyPaymentCreditRequest\x1a&.settlement.ApplyPaymentCreditResponse\x12c\n" +
	"\x12ApplyPaymentRefund\x12%.settlement.ApplyPaymentRefundRequest\x1a&.settlement.ApplyPaymentRefundResponse\x12o\n" +
	"\x16ApplyPaymentChargeback\x12).settlement.ApplyPaymentChargebackRequest\x1a*.settlement.ApplyPaymentChargebackResponse\x12\x87\x01\n" +
	"\x1eApplyPaymentChargebackReversal\x121.settlement.ApplyPaymentChargebackReversalRequest\x1a2.settlement.ApplyPaymentChargebackReversalResponse\x12W\n" +
	"\x0eGetLedgerEntry\x12!.settlement.GetLedgerEntryRequest\x1a\".settlement.GetLedgerEntryResponseB Z\x1eespx/internal/management/pb;pbb\x06proto3"

var (
	file_settlement_proto_rawDescOnce sync.Once
	file_settlement_proto_rawDescData []byte
)

func file_settlement_proto_rawDescGZIP() []byte {
	file_settlement_proto_rawDescOnce.Do(func() {
		file_settlement_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_settlement_proto_rawDesc), len(file_settlement_proto_rawDesc)))
	})
	return file_settlement_proto_rawDescData
}

var file_settlement_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_settlement_proto_goTypes = []any{
	(*ApplyPaymentCreditRequest)(nil),              // 0: settlement.ApplyPaymentCreditRequest
	(*ApplyPaymentCreditResponse)(nil),             // 1: settlement.ApplyPaymentCreditResponse
	(*ApplyPaymentRefundRequest)(nil),              // 2: settlement.ApplyPaymentRefundRequest
	(*ApplyPaymentRefundResponse)(nil),             // 3: settlement.ApplyPaymentRefundResponse
	(*ApplyPaymentChargebackRequest)(nil),          // 4: settlement.ApplyPaymentChargebackRequest
	(*ApplyPaymentChargebackResponse)(nil),         // 5: settlement.ApplyPaymentChargebackResponse
	(*ApplyPaymentChargebackReversalRequest)(nil),  // 6: settlement.ApplyPaymentChargebackReversalRequest
	(*ApplyPaymentChargebackReversalResponse)(nil), // 7: settlement.ApplyPaymentChargebackReversalResponse
	(*GetLedgerEntryRequest)(nil),                  // 8: settlement.GetLedgerEntryRequest
	(*LedgerEntry)(nil),                            // 9: settlement.LedgerEntry
	(*GetLedgerEntryResponse)(nil),                 // 10: settlement.GetLedgerEntryResponse
}
var file_settlement_proto_depIdxs = []int32{
	9,  // 0: settlement.GetLedgerEntryResponse.topup:type_name -> settlement.LedgerEntry
	0,  // 1: settlement.SettlementService.ApplyPaymentCredit:input_type -> settlement.ApplyPaymentCreditRequest
	2,  // 2: settlement.SettlementService.ApplyPaymentRefund:input_type -> settlement.ApplyPaymentRefundRequest
	4,  // 3: settlement.SettlementService.ApplyPaymentChargeback:input_type -> settlement.ApplyPaymentChargebackRequest
	6,  // 4: settlement.SettlementService.ApplyPaymentChargebackReversal:input_type -> settlement.ApplyPaymentChargebackReversalRequest
	8,  // 5: settlement.SettlementService.GetLedgerEntry:input_type -> settlement.GetLedgerEntryRequest
	1,  // 6: settlement.SettlementService.ApplyPaymentCredit:output_type -> settlement.ApplyPaymentCreditResponse
	3,  // 7: settlement.SettlementService.ApplyPaymentRefund:output_type -> settlement.ApplyPaymentRefundResponse
	5,  // 8: settlement.SettlementService.ApplyPaymentChargeback:output_type -> settlement.ApplyPaymentChargebackResponse
	7,  // 9: settlement.SettlementService.ApplyPaymentChargebackReversal:output_type -> settlement.ApplyPaymentChargebackReversalResponse
	10, // 10: settlement.SettlementService.GetLedgerEntry:output_type -> settlement.GetLedgerEntryResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_settlement_proto_init() }
func file_settlement_proto_init() {
	if File_settlement_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_settlement_proto_rawDesc), len(file_settlement_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_settlement_proto_goTypes,
		DependencyIndexes: file_settlement_proto_depIdxs,
		MessageInfos:      file_settlement_proto_msgTypes,
	}.Build()
	File_settlement_proto = out.File
	file_settlement_proto_goTypes = nil
	file_settlement_proto_depIdxs = nil
}
