// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: settlement.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApplyPaymentCreditRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	CustomerId           string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	AmountMicro          int64                  `protobuf:"varint,2,opt,name=amount_micro,json=amountMicro,proto3" json:"amount_micro,omitempty"`
	LedgerIdempotencyKey string                 `protobuf:"bytes,3,opt,name=ledger_idempotency_key,json=ledgerIdempotencyKey,proto3" json:"ledger_idempotency_key,omitempty"` // e.g. "stripe:evt_01H..."
	PaymentIntentId      string                 `protobuf:"bytes,4,opt,name=payment_intent_id,json=paymentIntentId,proto3" json:"payment_intent_id,omitempty"`
	Provider             string                 `protobuf:"bytes,5,opt,name=provider,proto3" json:"provider,omitempty"`
	ProviderRef          string                 `protobuf:"bytes,6,opt,name=provider_ref,json=providerRef,proto3" json:"provider_ref,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ApplyPaymentCreditRequest) Reset() {
	*x = ApplyPaymentCreditRequest{}
	mi := &file_settlement_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyPaymentCreditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyPaymentCreditRequest) ProtoMessage() {}

func (x *ApplyPaymentCreditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_settlement_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyPaymentCreditRequest.ProtoReflect.Descriptor instead.
func (*ApplyPaymentCreditRequest) Descriptor() ([]byte, []int) {
	return file_settlement_proto_rawDescGZIP(), []int{0}
}

func (x *ApplyPaymentCreditRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *ApplyPaymentCreditRequest) GetAmountMicro() int64 {
	if x != nil {
		return x.AmountMicro
	}
	return 0
}

func (x *ApplyPaymentCreditRequest) GetLedgerIdempotencyKey() string {
	if x != nil {
		return x.LedgerIdempotencyKey
	}
	return ""
}

func (x *ApplyPaymentCreditRequest) GetPaymentIntentId() string {
	if x != nil {
		return x.PaymentIntentId
	}
	return ""
}

func (x *ApplyPaymentCreditRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ApplyPaymentCreditRequest) GetProviderRef() string {
	if x != nil {
		return x.ProviderRef
	}
	return ""
}

type ApplyPaymentCreditResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Applied       bool                   `protobuf:"varint,1,opt,name=applied,proto3" json:"applied,omitempty"` // false = duplicate idempotency hit (still success)
	LedgerEntryId int64                  `protobuf:"varint,2,opt,name=ledger_entry_id,json=ledgerEntryId,proto3" json:"ledger_entry_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyPaymentCreditResponse) Reset() {
	*x = ApplyPaymentCreditResponse{}
	mi := &file_settlement_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyPaymentCreditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyPaymentCreditResponse) ProtoMessage() {}

func (x *ApplyPaymentCreditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_settlement_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyPaymentCreditResponse.ProtoReflect.Descriptor instead.
func (*ApplyPaymentCreditResponse) Descriptor() ([]byte, []int) {
	return file_settlement_proto_rawDescGZIP(), []int{1}
}

func (x *ApplyPaymentCreditResponse) GetApplied() bool {
	if x != nil {
		return x.Applied
	}
	return false
}

func (x *ApplyPaymentCreditResponse) GetLedgerEntryId() int64 {
	if x != nil {
		return x.LedgerEntryId
	}
	return 0
}

var File_settlement_proto protoreflect.FileDescriptor

const file_settlement_proto_rawDesc = "" +
	"\n" +
	"\x10settlement.proto\x12\n" +
	"settlement\"\x80\x02\n" +
	"\x19ApplyPaymentCreditRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12!\n" +
	"\famount_micro\x18\x02 \x01(\x03R\vamountMicro\x124\n" +
	"\x16ledger_idempotency_key\x18\x03 \x01(\tR\x14ledgerIdempotencyKey\x12*\n" +
	"\x11payment_intent_id\x18\x04 \x01(\tR\x0fpaymentIntentId\x12\x1a\n" +
	"\bprovider\x18\x05 \x01(\tR\bprovider\x12!\n" +
	"\fprovider_ref\x18\x06 \x01(\tR\vproviderRef\"^\n" +
	"\x1aApplyPaymentCreditResponse\x12\x18\n" +
	"\aapplied\x18\x01 \x01(\bR\aapplied\x12&\n" +
	"\x0fledger_entry_id\x18\x02 \x01(\x03R\rledgerEntryId2x\n" +
	"\x11SettlementService\x12c\n" +
	"\x12ApplyPaymentCredit\x12%.settlement.ApplyPaymentCreditRequest\x1a&.settlement.ApplyPaymentCreditResponseB Z\x1eespx/internal/management/pb;pbb\x06proto3"

var (
	file_settlement_proto_rawDescOnce sync.Once
	file_settlement_proto_rawDescData []byte
)

func file_settlement_proto_rawDescGZIP() []byte {
	file_settlement_proto_rawDescOnce.Do(func() {
		file_settlement_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_settlement_proto_rawDesc), len(file_settlement_proto_rawDesc)))
	})
	return file_settlement_proto_rawDescData
}

var file_settlement_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_settlement_proto_goTypes = []any{
	(*ApplyPaymentCreditRequest)(nil),  // 0: settlement.ApplyPaymentCreditRequest
	(*ApplyPaymentCreditResponse)(nil), // 1: settlement.ApplyPaymentCreditResponse
}
var file_settlement_proto_depIdxs = []int32{
	0, // 0: settlement.SettlementService.ApplyPaymentCredit:input_type -> settlement.ApplyPaymentCreditRequest
	1, // 1: settlement.SettlementService.ApplyPaymentCredit:output_type -> settlement.ApplyPaymentCreditResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_settlement_proto_init() }
func file_settlement_proto_init() {
	if File_settlement_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_settlement_proto_rawDesc), len(file_settlement_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_settlement_proto_goTypes,
		DependencyIndexes: file_settlement_proto_depIdxs,
		MessageInfos:      file_settlement_proto_msgTypes,
	}.Build()
	File_settlement_proto = out.File
	file_settlement_proto_goTypes = nil
	file_settlement_proto_depIdxs = nil
}
