// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/proto/events.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    []byte                 `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	EventType     []byte                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Metadata      *EventMetadata         `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdEvent) Reset() {
	*x = AdEvent{}
	mi := &file_api_proto_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdEvent) ProtoMessage() {}

func (x *AdEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdEvent.ProtoReflect.Descriptor instead.
func (*AdEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_events_proto_rawDescGZIP(), []int{0}
}

func (x *AdEvent) GetCampaignId() []byte {
	if x != nil {
		return x.CampaignId
	}
	return nil
}

func (x *AdEvent) GetEventType() []byte {
	if x != nil {
		return x.EventType
	}
	return nil
}

func (x *AdEvent) GetMetadata() *EventMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type EventMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClickId       []byte                 `protobuf:"bytes,1,opt,name=click_id,json=clickId,proto3" json:"click_id,omitempty"`
	UserId        []byte                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceType    []byte                 `protobuf:"bytes,3,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	Os            []byte                 `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`
	Extra         map[string]string      `protobuf:"bytes,5,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ExtraBytes    []byte                 `protobuf:"bytes,6,opt,name=extra_bytes,json=extraBytes,proto3" json:"extra_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventMetadata) Reset() {
	*x = EventMetadata{}
	mi := &file_api_proto_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMetadata) ProtoMessage() {}

func (x *EventMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMetadata.ProtoReflect.Descriptor instead.
func (*EventMetadata) Descriptor() ([]byte, []int) {
	return file_api_proto_events_proto_rawDescGZIP(), []int{1}
}

func (x *EventMetadata) GetClickId() []byte {
	if x != nil {
		return x.ClickId
	}
	return nil
}

func (x *EventMetadata) GetUserId() []byte {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *EventMetadata) GetDeviceType() []byte {
	if x != nil {
		return x.DeviceType
	}
	return nil
}

func (x *EventMetadata) GetOs() []byte {
	if x != nil {
		return x.Os
	}
	return nil
}

func (x *EventMetadata) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

func (x *EventMetadata) GetExtraBytes() []byte {
	if x != nil {
		return x.ExtraBytes
	}
	return nil
}

type TrackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackResponse) Reset() {
	*x = TrackResponse{}
	mi := &file_api_proto_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackResponse) ProtoMessage() {}

func (x *TrackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackResponse.ProtoReflect.Descriptor instead.
func (*TrackResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_events_proto_rawDescGZIP(), []int{2}
}

func (x *TrackResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *TrackResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type AdStreamEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClickId       []byte                 `protobuf:"bytes,1,opt,name=click_id,json=clickId,proto3" json:"click_id,omitempty"`
	CampaignId    []byte                 `protobuf:"bytes,2,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	EventType     []byte                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Ip            []byte                 `protobuf:"bytes,5,opt,name=ip,proto3" json:"ip,omitempty"`
	Ua            []byte                 `protobuf:"bytes,6,opt,name=ua,proto3" json:"ua,omitempty"`
	CreatedAtUnix int64                  `protobuf:"varint,7,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdStreamEvent) Reset() {
	*x = AdStreamEvent{}
	mi := &file_api_proto_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdStreamEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdStreamEvent) ProtoMessage() {}

func (x *AdStreamEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdStreamEvent.ProtoReflect.Descriptor instead.
func (*AdStreamEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_events_proto_rawDescGZIP(), []int{3}
}

func (x *AdStreamEvent) GetClickId() []byte {
	if x != nil {
		return x.ClickId
	}
	return nil
}

func (x *AdStreamEvent) GetCampaignId() []byte {
	if x != nil {
		return x.CampaignId
	}
	return nil
}

func (x *AdStreamEvent) GetEventType() []byte {
	if x != nil {
		return x.EventType
	}
	return nil
}

func (x *AdStreamEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AdStreamEvent) GetIp() []byte {
	if x != nil {
		return x.Ip
	}
	return nil
}

func (x *AdStreamEvent) GetUa() []byte {
	if x != nil {
		return x.Ua
	}
	return nil
}

func (x *AdStreamEvent) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

type AdDLQEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalEvent *AdStreamEvent         `protobuf:"bytes,1,opt,name=original_event,json=originalEvent,proto3" json:"original_event,omitempty"`
	Error         []byte                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	OriginalId    []byte                 `protobuf:"bytes,3,opt,name=original_id,json=originalId,proto3" json:"original_id,omitempty"`
	FailedAtUnix  int64                  `protobuf:"varint,4,opt,name=failed_at_unix,json=failedAtUnix,proto3" json:"failed_at_unix,omitempty"`
	WorkerId      []byte                 `protobuf:"bytes,5,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	RetryCount    int32                  `protobuf:"varint,6,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdDLQEvent) Reset() {
	*x = AdDLQEvent{}
	mi := &file_api_proto_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdDLQEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdDLQEvent) ProtoMessage() {}

func (x *AdDLQEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdDLQEvent.ProtoReflect.Descriptor instead.
func (*AdDLQEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_events_proto_rawDescGZIP(), []int{4}
}

func (x *AdDLQEvent) GetOriginalEvent() *AdStreamEvent {
	if x != nil {
		return x.OriginalEvent
	}
	return nil
}

func (x *AdDLQEvent) GetError() []byte {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *AdDLQEvent) GetOriginalId() []byte {
	if x != nil {
		return x.OriginalId
	}
	return nil
}

func (x *AdDLQEvent) GetFailedAtUnix() int64 {
	if x != nil {
		return x.FailedAtUnix
	}
	return 0
}

func (x *AdDLQEvent) GetWorkerId() []byte {
	if x != nil {
		return x.WorkerId
	}
	return nil
}

func (x *AdDLQEvent) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

type AdLogRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampUnix int64                  `protobuf:"varint,1,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	CampaignId    []byte                 `protobuf:"bytes,2,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	ClickId       []byte                 `protobuf:"bytes,3,opt,name=click_id,json=clickId,proto3" json:"click_id,omitempty"`
	EventType     []byte                 `protobuf:"bytes,4,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Priority      uint32                 `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdLogRecord) Reset() {
	*x = AdLogRecord{}
	mi := &file_api_proto_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdLogRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdLogRecord) ProtoMessage() {}

func (x *AdLogRecord) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdLogRecord.ProtoReflect.Descriptor instead.
func (*AdLogRecord) Descriptor() ([]byte, []int) {
	return file_api_proto_events_proto_rawDescGZIP(), []int{5}
}

func (x *AdLogRecord) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

func (x *AdLogRecord) GetCampaignId() []byte {
	if x != nil {
		return x.CampaignId
	}
	return nil
}

func (x *AdLogRecord) GetClickId() []byte {
	if x != nil {
		return x.ClickId
	}
	return nil
}

func (x *AdLogRecord) GetEventType() []byte {
	if x != nil {
		return x.EventType
	}
	return nil
}

func (x *AdLogRecord) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

var File_api_proto_events_proto protoreflect.FileDescriptor

const file_api_proto_events_proto_rawDesc = "" +
	"\n" +
	"\x16api/proto/events.proto\x12\x06ads.v1\"|\n" +
	"\aAdEvent\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\fR\n" +
	"campaignId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\fR\teventType\x121\n" +
	"\bmetadata\x18\x03 \x01(\v2\x15.ads.v1.EventMetadataR\bmetadata\"\x87\x02\n" +
	"\rEventMetadata\x12\x19\n" +
	"\bclick_id\x18\x01 \x01(\fR\aclickId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\fR\x06userId\x12\x1f\n" +
	"\vdevice_type\x18\x03 \x01(\fR\n" +
	"deviceType\x12\x0e\n" +
	"\x02os\x18\x04 \x01(\fR\x02os\x126\n" +
	"\x05extra\x18\x05 \x03(\v2 .ads.v1.EventMetadata.ExtraEntryR\x05extra\x12\x1f\n" +
	"\vextra_bytes\x18\x06 \x01(\fR\n" +
	"extraBytes\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"F\n" +
	"\rTrackResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\xcc\x01\n" +
	"\rAdStreamEvent\x12\x19\n" +
	"\bclick_id\x18\x01 \x01(\fR\aclickId\x12\x1f\n" +
	"\vcampaign_id\x18\x02 \x01(\fR\n" +
	"campaignId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\fR\teventType\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12\x0e\n" +
	"\x02ip\x18\x05 \x01(\fR\x02ip\x12\x0e\n" +
	"\x02ua\x18\x06 \x01(\fR\x02ua\x12&\n" +
	"\x0fcreated_at_unix\x18\a \x01(\x03R\rcreatedAtUnix\"\xe5\x01\n" +
	"\n" +
	"AdDLQEvent\x12<\n" +
	"\x0eoriginal_event\x18\x01 \x01(\v2\x15.ads.v1.AdStreamEventR\roriginalEvent\x12\x14\n" +
	"\x05error\x18\x02 \x01(\fR\x05error\x12\x1f\n" +
	"\voriginal_id\x18\x03 \x01(\fR\n" +
	"originalId\x12$\n" +
	"\x0efailed_at_unix\x18\x04 \x01(\x03R\ffailedAtUnix\x12\x1b\n" +
	"\tworker_id\x18\x05 \x01(\fR\bworkerId\x12\x1f\n" +
	"\vretry_count\x18\x06 \x01(\x05R\n" +
	"retryCount\"\xab\x01\n" +
	"\vAdLogRecord\x12%\n" +
	"\x0etimestamp_unix\x18\x01 \x01(\x03R\rtimestampUnix\x12\x1f\n" +
	"\vcampaign_id\x18\x02 \x01(\fR\n" +
	"campaignId\x12\x19\n" +
	"\bclick_id\x18\x03 \x01(\fR\aclickId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x04 \x01(\fR\teventType\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\rR\bpriorityB<Z:github.com/mykhailov-ua/ad-event-processor/internal/ads/pbb\x06proto3"

var (
	file_api_proto_events_proto_rawDescOnce sync.Once
	file_api_proto_events_proto_rawDescData []byte
)

func file_api_proto_events_proto_rawDescGZIP() []byte {
	file_api_proto_events_proto_rawDescOnce.Do(func() {
		file_api_proto_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_events_proto_rawDesc), len(file_api_proto_events_proto_rawDesc)))
	})
	return file_api_proto_events_proto_rawDescData
}

var file_api_proto_events_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_proto_events_proto_goTypes = []any{
	(*AdEvent)(nil),       // 0: ads.v1.AdEvent
	(*EventMetadata)(nil), // 1: ads.v1.EventMetadata
	(*TrackResponse)(nil), // 2: ads.v1.TrackResponse
	(*AdStreamEvent)(nil), // 3: ads.v1.AdStreamEvent
	(*AdDLQEvent)(nil),    // 4: ads.v1.AdDLQEvent
	(*AdLogRecord)(nil),   // 5: ads.v1.AdLogRecord
	nil,                   // 6: ads.v1.EventMetadata.ExtraEntry
}
var file_api_proto_events_proto_depIdxs = []int32{
	1, // 0: ads.v1.AdEvent.metadata:type_name -> ads.v1.EventMetadata
	6, // 1: ads.v1.EventMetadata.extra:type_name -> ads.v1.EventMetadata.ExtraEntry
	3, // 2: ads.v1.AdDLQEvent.original_event:type_name -> ads.v1.AdStreamEvent
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_events_proto_init() }
func file_api_proto_events_proto_init() {
	if File_api_proto_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_events_proto_rawDesc), len(file_api_proto_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_events_proto_goTypes,
		DependencyIndexes: file_api_proto_events_proto_depIdxs,
		MessageInfos:      file_api_proto_events_proto_msgTypes,
	}.Build()
	File_api_proto_events_proto = out.File
	file_api_proto_events_proto_goTypes = nil
	file_api_proto_events_proto_depIdxs = nil
}
