// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: delivery.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimScheduledCampaignForUpdate = `-- name: ClaimScheduledCampaignForUpdate :one
SELECT id, name, status, budget_limit, created_at, updated_at, customer_id, current_spend, deleted_at, pacing_mode, daily_budget, timezone, freq_limit, freq_window, target_countries, brand_id, brand_fcap_key, start_at, end_at, daypart_hours, template_id, fraud_threshold_pass, fraud_threshold_suspect, fraud_threshold_ivt, fraud_threshold_block, ghost_ivt_enabled, behavior_flags, supply_chain_nodes, require_consent_purposes, migration_gen FROM campaigns
WHERE deleted_at IS NULL
  AND status IN ('ACTIVE', 'PAUSED')
  AND (start_at IS NOT NULL OR end_at IS NOT NULL)
ORDER BY updated_at ASC
LIMIT 1
FOR UPDATE SKIP LOCKED
`

func (q *Queries) ClaimScheduledCampaignForUpdate(ctx context.Context) (Campaign, error) {
	row := q.db.QueryRow(ctx, claimScheduledCampaignForUpdate)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.BudgetLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomerID,
		&i.CurrentSpend,
		&i.DeletedAt,
		&i.PacingMode,
		&i.DailyBudget,
		&i.Timezone,
		&i.FreqLimit,
		&i.FreqWindow,
		&i.TargetCountries,
		&i.BrandID,
		&i.BrandFcapKey,
		&i.StartAt,
		&i.EndAt,
		&i.DaypartHours,
		&i.TemplateID,
		&i.FraudThresholdPass,
		&i.FraudThresholdSuspect,
		&i.FraudThresholdIvt,
		&i.FraudThresholdBlock,
		&i.GhostIvtEnabled,
		&i.BehaviorFlags,
		&i.SupplyChainNodes,
		&i.RequireConsentPurposes,
		&i.MigrationGen,
	)
	return i, err
}

const countCampaignTemplates = `-- name: CountCampaignTemplates :one
SELECT COUNT(*) FROM campaign_templates WHERE customer_id = $1
`

func (q *Queries) CountCampaignTemplates(ctx context.Context, customerID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCampaignTemplates, customerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBrandCreative = `-- name: CreateBrandCreative :one

INSERT INTO brand_creatives (id, brand_id, name, landing_url, weight, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, brand_id, name, landing_url, weight, status, created_at, updated_at
`

type CreateBrandCreativeParams struct {
	ID         pgtype.UUID `json:"id"`
	BrandID    pgtype.UUID `json:"brand_id"`
	Name       string      `json:"name"`
	LandingUrl string      `json:"landing_url"`
	Weight     int32       `json:"weight"`
	Status     string      `json:"status"`
}

// Brand creatives
func (q *Queries) CreateBrandCreative(ctx context.Context, arg CreateBrandCreativeParams) (BrandCreative, error) {
	row := q.db.QueryRow(ctx, createBrandCreative,
		arg.ID,
		arg.BrandID,
		arg.Name,
		arg.LandingUrl,
		arg.Weight,
		arg.Status,
	)
	var i BrandCreative
	err := row.Scan(
		&i.ID,
		&i.BrandID,
		&i.Name,
		&i.LandingUrl,
		&i.Weight,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCampaignTemplate = `-- name: CreateCampaignTemplate :one

INSERT INTO campaign_templates (
    id, customer_id, name, budget_limit, pacing_mode, daily_budget, timezone,
    freq_limit, freq_window, target_countries, brand_id, daypart_hours
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, customer_id, name, budget_limit, pacing_mode, daily_budget, timezone, freq_limit, freq_window, target_countries, brand_id, daypart_hours, created_at, updated_at
`

type CreateCampaignTemplateParams struct {
	ID              pgtype.UUID    `json:"id"`
	CustomerID      pgtype.UUID    `json:"customer_id"`
	Name            string         `json:"name"`
	BudgetLimit     int64          `json:"budget_limit"`
	PacingMode      PacingModeType `json:"pacing_mode"`
	DailyBudget     int64          `json:"daily_budget"`
	Timezone        string         `json:"timezone"`
	FreqLimit       int32          `json:"freq_limit"`
	FreqWindow      int32          `json:"freq_window"`
	TargetCountries []string       `json:"target_countries"`
	BrandID         pgtype.UUID    `json:"brand_id"`
	DaypartHours    []int16        `json:"daypart_hours"`
}

// Campaign templates
func (q *Queries) CreateCampaignTemplate(ctx context.Context, arg CreateCampaignTemplateParams) (CampaignTemplate, error) {
	row := q.db.QueryRow(ctx, createCampaignTemplate,
		arg.ID,
		arg.CustomerID,
		arg.Name,
		arg.BudgetLimit,
		arg.PacingMode,
		arg.DailyBudget,
		arg.Timezone,
		arg.FreqLimit,
		arg.FreqWindow,
		arg.TargetCountries,
		arg.BrandID,
		arg.DaypartHours,
	)
	var i CampaignTemplate
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Name,
		&i.BudgetLimit,
		&i.PacingMode,
		&i.DailyBudget,
		&i.Timezone,
		&i.FreqLimit,
		&i.FreqWindow,
		&i.TargetCountries,
		&i.BrandID,
		&i.DaypartHours,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBrandCreative = `-- name: DeleteBrandCreative :exec
DELETE FROM brand_creatives WHERE id = $1
`

func (q *Queries) DeleteBrandCreative(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBrandCreative, id)
	return err
}

const getBrandCreative = `-- name: GetBrandCreative :one
SELECT id, brand_id, name, landing_url, weight, status, created_at, updated_at FROM brand_creatives WHERE id = $1
`

func (q *Queries) GetBrandCreative(ctx context.Context, id pgtype.UUID) (BrandCreative, error) {
	row := q.db.QueryRow(ctx, getBrandCreative, id)
	var i BrandCreative
	err := row.Scan(
		&i.ID,
		&i.BrandID,
		&i.Name,
		&i.LandingUrl,
		&i.Weight,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCampaignTemplate = `-- name: GetCampaignTemplate :one
SELECT id, customer_id, name, budget_limit, pacing_mode, daily_budget, timezone, freq_limit, freq_window, target_countries, brand_id, daypart_hours, created_at, updated_at FROM campaign_templates WHERE id = $1
`

func (q *Queries) GetCampaignTemplate(ctx context.Context, id pgtype.UUID) (CampaignTemplate, error) {
	row := q.db.QueryRow(ctx, getCampaignTemplate, id)
	var i CampaignTemplate
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Name,
		&i.BudgetLimit,
		&i.PacingMode,
		&i.DailyBudget,
		&i.Timezone,
		&i.FreqLimit,
		&i.FreqWindow,
		&i.TargetCountries,
		&i.BrandID,
		&i.DaypartHours,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveBrandCreatives = `-- name: ListActiveBrandCreatives :many
SELECT id, brand_id, name, landing_url, weight, status, created_at, updated_at FROM brand_creatives
WHERE brand_id = $1 AND status = 'ACTIVE'
ORDER BY created_at ASC
`

func (q *Queries) ListActiveBrandCreatives(ctx context.Context, brandID pgtype.UUID) ([]BrandCreative, error) {
	rows, err := q.db.Query(ctx, listActiveBrandCreatives, brandID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BrandCreative
	for rows.Next() {
		var i BrandCreative
		if err := rows.Scan(
			&i.ID,
			&i.BrandID,
			&i.Name,
			&i.LandingUrl,
			&i.Weight,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBrandCreatives = `-- name: ListBrandCreatives :many
SELECT id, brand_id, name, landing_url, weight, status, created_at, updated_at FROM brand_creatives
WHERE brand_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListBrandCreatives(ctx context.Context, brandID pgtype.UUID) ([]BrandCreative, error) {
	rows, err := q.db.Query(ctx, listBrandCreatives, brandID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BrandCreative
	for rows.Next() {
		var i BrandCreative
		if err := rows.Scan(
			&i.ID,
			&i.BrandID,
			&i.Name,
			&i.LandingUrl,
			&i.Weight,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCampaignIDsByBrand = `-- name: ListCampaignIDsByBrand :many
SELECT id FROM campaigns
WHERE brand_id = $1 AND deleted_at IS NULL AND status IN ('ACTIVE', 'PAUSED')
`

func (q *Queries) ListCampaignIDsByBrand(ctx context.Context, brandID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listCampaignIDsByBrand, brandID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCampaignTemplates = `-- name: ListCampaignTemplates :many
SELECT id, customer_id, name, budget_limit, pacing_mode, daily_budget, timezone, freq_limit, freq_window, target_countries, brand_id, daypart_hours, created_at, updated_at FROM campaign_templates
WHERE customer_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListCampaignTemplatesParams struct {
	CustomerID pgtype.UUID `json:"customer_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

func (q *Queries) ListCampaignTemplates(ctx context.Context, arg ListCampaignTemplatesParams) ([]CampaignTemplate, error) {
	rows, err := q.db.Query(ctx, listCampaignTemplates, arg.CustomerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CampaignTemplate
	for rows.Next() {
		var i CampaignTemplate
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.Name,
			&i.BudgetLimit,
			&i.PacingMode,
			&i.DailyBudget,
			&i.Timezone,
			&i.FreqLimit,
			&i.FreqWindow,
			&i.TargetCountries,
			&i.BrandID,
			&i.DaypartHours,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistinctBrandsWithActiveCreatives = `-- name: ListDistinctBrandsWithActiveCreatives :many
SELECT DISTINCT brand_id FROM brand_creatives WHERE status = 'ACTIVE'
`

func (q *Queries) ListDistinctBrandsWithActiveCreatives(ctx context.Context) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listDistinctBrandsWithActiveCreatives)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var brand_id pgtype.UUID
		if err := rows.Scan(&brand_id); err != nil {
			return nil, err
		}
		items = append(items, brand_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduledCampaigns = `-- name: ListScheduledCampaigns :many
SELECT id, name, status, budget_limit, created_at, updated_at, customer_id, current_spend, deleted_at, pacing_mode, daily_budget, timezone, freq_limit, freq_window, target_countries, brand_id, brand_fcap_key, start_at, end_at, daypart_hours, template_id, fraud_threshold_pass, fraud_threshold_suspect, fraud_threshold_ivt, fraud_threshold_block, ghost_ivt_enabled, behavior_flags, supply_chain_nodes, require_consent_purposes, migration_gen FROM campaigns
WHERE deleted_at IS NULL
  AND status IN ('ACTIVE', 'PAUSED')
  AND (start_at IS NOT NULL OR end_at IS NOT NULL)
ORDER BY updated_at ASC
LIMIT $1
`

func (q *Queries) ListScheduledCampaigns(ctx context.Context, limit int32) ([]Campaign, error) {
	rows, err := q.db.Query(ctx, listScheduledCampaigns, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Campaign
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.BudgetLimit,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CustomerID,
			&i.CurrentSpend,
			&i.DeletedAt,
			&i.PacingMode,
			&i.DailyBudget,
			&i.Timezone,
			&i.FreqLimit,
			&i.FreqWindow,
			&i.TargetCountries,
			&i.BrandID,
			&i.BrandFcapKey,
			&i.StartAt,
			&i.EndAt,
			&i.DaypartHours,
			&i.TemplateID,
			&i.FraudThresholdPass,
			&i.FraudThresholdSuspect,
			&i.FraudThresholdIvt,
			&i.FraudThresholdBlock,
			&i.GhostIvtEnabled,
			&i.BehaviorFlags,
			&i.SupplyChainNodes,
			&i.RequireConsentPurposes,
			&i.MigrationGen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pauseCampaign = `-- name: PauseCampaign :one
UPDATE campaigns
SET status = 'PAUSED',
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND status IN ('ACTIVE', 'EXHAUSTED')
RETURNING id, name, status, budget_limit, created_at, updated_at, customer_id, current_spend, deleted_at, pacing_mode, daily_budget, timezone, freq_limit, freq_window, target_countries, brand_id, brand_fcap_key, start_at, end_at, daypart_hours, template_id, fraud_threshold_pass, fraud_threshold_suspect, fraud_threshold_ivt, fraud_threshold_block, ghost_ivt_enabled, behavior_flags, supply_chain_nodes, require_consent_purposes, migration_gen
`

func (q *Queries) PauseCampaign(ctx context.Context, id pgtype.UUID) (Campaign, error) {
	row := q.db.QueryRow(ctx, pauseCampaign, id)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.BudgetLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomerID,
		&i.CurrentSpend,
		&i.DeletedAt,
		&i.PacingMode,
		&i.DailyBudget,
		&i.Timezone,
		&i.FreqLimit,
		&i.FreqWindow,
		&i.TargetCountries,
		&i.BrandID,
		&i.BrandFcapKey,
		&i.StartAt,
		&i.EndAt,
		&i.DaypartHours,
		&i.TemplateID,
		&i.FraudThresholdPass,
		&i.FraudThresholdSuspect,
		&i.FraudThresholdIvt,
		&i.FraudThresholdBlock,
		&i.GhostIvtEnabled,
		&i.BehaviorFlags,
		&i.SupplyChainNodes,
		&i.RequireConsentPurposes,
		&i.MigrationGen,
	)
	return i, err
}

const resumeCampaign = `-- name: ResumeCampaign :one
UPDATE campaigns
SET status = 'ACTIVE',
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND status = 'PAUSED'
RETURNING id, name, status, budget_limit, created_at, updated_at, customer_id, current_spend, deleted_at, pacing_mode, daily_budget, timezone, freq_limit, freq_window, target_countries, brand_id, brand_fcap_key, start_at, end_at, daypart_hours, template_id, fraud_threshold_pass, fraud_threshold_suspect, fraud_threshold_ivt, fraud_threshold_block, ghost_ivt_enabled, behavior_flags, supply_chain_nodes, require_consent_purposes, migration_gen
`

func (q *Queries) ResumeCampaign(ctx context.Context, id pgtype.UUID) (Campaign, error) {
	row := q.db.QueryRow(ctx, resumeCampaign, id)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.BudgetLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomerID,
		&i.CurrentSpend,
		&i.DeletedAt,
		&i.PacingMode,
		&i.DailyBudget,
		&i.Timezone,
		&i.FreqLimit,
		&i.FreqWindow,
		&i.TargetCountries,
		&i.BrandID,
		&i.BrandFcapKey,
		&i.StartAt,
		&i.EndAt,
		&i.DaypartHours,
		&i.TemplateID,
		&i.FraudThresholdPass,
		&i.FraudThresholdSuspect,
		&i.FraudThresholdIvt,
		&i.FraudThresholdBlock,
		&i.GhostIvtEnabled,
		&i.BehaviorFlags,
		&i.SupplyChainNodes,
		&i.RequireConsentPurposes,
		&i.MigrationGen,
	)
	return i, err
}

const updateBrandCreative = `-- name: UpdateBrandCreative :one
UPDATE brand_creatives
SET name = $2,
    landing_url = $3,
    weight = $4,
    status = $5,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, brand_id, name, landing_url, weight, status, created_at, updated_at
`

type UpdateBrandCreativeParams struct {
	ID         pgtype.UUID `json:"id"`
	Name       string      `json:"name"`
	LandingUrl string      `json:"landing_url"`
	Weight     int32       `json:"weight"`
	Status     string      `json:"status"`
}

func (q *Queries) UpdateBrandCreative(ctx context.Context, arg UpdateBrandCreativeParams) (BrandCreative, error) {
	row := q.db.QueryRow(ctx, updateBrandCreative,
		arg.ID,
		arg.Name,
		arg.LandingUrl,
		arg.Weight,
		arg.Status,
	)
	var i BrandCreative
	err := row.Scan(
		&i.ID,
		&i.BrandID,
		&i.Name,
		&i.LandingUrl,
		&i.Weight,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCampaignSchedule = `-- name: UpdateCampaignSchedule :one

UPDATE campaigns
SET start_at = $2,
    end_at = $3,
    daypart_hours = $4,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, status, budget_limit, created_at, updated_at, customer_id, current_spend, deleted_at, pacing_mode, daily_budget, timezone, freq_limit, freq_window, target_countries, brand_id, brand_fcap_key, start_at, end_at, daypart_hours, template_id, fraud_threshold_pass, fraud_threshold_suspect, fraud_threshold_ivt, fraud_threshold_block, ghost_ivt_enabled, behavior_flags, supply_chain_nodes, require_consent_purposes, migration_gen
`

type UpdateCampaignScheduleParams struct {
	ID           pgtype.UUID        `json:"id"`
	StartAt      pgtype.Timestamptz `json:"start_at"`
	EndAt        pgtype.Timestamptz `json:"end_at"`
	DaypartHours []int16            `json:"daypart_hours"`
}

// Campaign schedule / lifecycle
func (q *Queries) UpdateCampaignSchedule(ctx context.Context, arg UpdateCampaignScheduleParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, updateCampaignSchedule,
		arg.ID,
		arg.StartAt,
		arg.EndAt,
		arg.DaypartHours,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.BudgetLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomerID,
		&i.CurrentSpend,
		&i.DeletedAt,
		&i.PacingMode,
		&i.DailyBudget,
		&i.Timezone,
		&i.FreqLimit,
		&i.FreqWindow,
		&i.TargetCountries,
		&i.BrandID,
		&i.BrandFcapKey,
		&i.StartAt,
		&i.EndAt,
		&i.DaypartHours,
		&i.TemplateID,
		&i.FraudThresholdPass,
		&i.FraudThresholdSuspect,
		&i.FraudThresholdIvt,
		&i.FraudThresholdBlock,
		&i.GhostIvtEnabled,
		&i.BehaviorFlags,
		&i.SupplyChainNodes,
		&i.RequireConsentPurposes,
		&i.MigrationGen,
	)
	return i, err
}
