// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AnonymizeConsentEventsByUserHash(ctx context.Context, userIDHash []byte) error
	AnonymizeEventsByUserID(ctx context.Context, userID pgtype.Text) error
	ClaimScheduledCampaignForUpdate(ctx context.Context) (Campaign, error)
	CleanupAuditLogs(ctx context.Context, createdAt pgtype.Timestamptz) error
	CleanupConsentEventsOlderThan(ctx context.Context, createdAt pgtype.Timestamptz) error
	ClearErasureSubjectUserID(ctx context.Context, id pgtype.UUID) error
	ConfigureBrandFcap(ctx context.Context, arg ConfigureBrandFcapParams) error
	CopySlotMapVersion(ctx context.Context, arg CopySlotMapVersionParams) error
	CountAuditLogs(ctx context.Context) (int64, error)
	CountBlacklist(ctx context.Context) (int64, error)
	CountCampaignTemplates(ctx context.Context, customerID pgtype.UUID) (int64, error)
	CountCampaigns(ctx context.Context, arg CountCampaignsParams) (int64, error)
	CountCustomerLedger(ctx context.Context, customerID pgtype.UUID) (int64, error)
	CountCustomers(ctx context.Context) (int64, error)
	CountManagementReconRuns(ctx context.Context) (int64, error)
	CountSlotMapRowsForVersion(ctx context.Context, version int32) (int32, error)
	CountStatusHistory(ctx context.Context, campaignID pgtype.UUID) (int64, error)
	CreateAdsTxtEntry(ctx context.Context, arg CreateAdsTxtEntryParams) (AdsTxtEntry, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AdminAuditLog, error)
	CreateBlacklistIP(ctx context.Context, arg CreateBlacklistIPParams) (IpBlacklist, error)
	CreateBrand(ctx context.Context, arg CreateBrandParams) (AdvertiserBrand, error)
	// Brand creatives
	CreateBrandCreative(ctx context.Context, arg CreateBrandCreativeParams) (BrandCreative, error)
	// events.sql: sqlc query definitions for campaign and event persistence.
	// All event writes target the PARTITION BY RANGE (created_date) table; callers
	// must supply created_date explicitly to guarantee correct partition routing.
	// ON CONFLICT (click_id, created_date) DO NOTHING provides idempotency within
	// the daily partition boundary.
	//
	// InsertEventsBatch is the primary batch-write path. The CTE uses RETURNING to
	// count only newly-inserted rows for campaign_stats aggregation; this prevents
	// double-counting when the same batch is retried. The EXISTS sub-select on campaigns
	// filters orphaned campaign_ids before the stats INSERT to avoid FK violations
	// rolling back the entire batch.
	CreateCampaign(ctx context.Context, arg CreateCampaignParams) (Campaign, error)
	// Campaign templates
	CreateCampaignTemplate(ctx context.Context, arg CreateCampaignTemplateParams) (CampaignTemplate, error)
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	CreateLedgerEntry(ctx context.Context, arg CreateLedgerEntryParams) (BalanceLedger, error)
	CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (OutboxEvent, error)
	// Privacy erasure (M6.4)
	CreatePrivacyErasureRequest(ctx context.Context, arg CreatePrivacyErasureRequestParams) (PrivacyErasureRequest, error)
	CreateReconRun(ctx context.Context, arg CreateReconRunParams) (ReconRun, error)
	CreateRtbDeal(ctx context.Context, arg CreateRtbDealParams) (RtbDeal, error)
	CreateSeller(ctx context.Context, arg CreateSellerParams) (Seller, error)
	CreateStatusHistory(ctx context.Context, arg CreateStatusHistoryParams) error
	DecreaseCampaignQuotaReserved(ctx context.Context, arg DecreaseCampaignQuotaReservedParams) error
	DeleteAdsTxtEntry(ctx context.Context, id int64) error
	DeleteBlacklistIP(ctx context.Context, ip string) error
	DeleteBrandCreative(ctx context.Context, id pgtype.UUID) error
	DeleteRtbDeal(ctx context.Context, id int64) error
	DeleteSeller(ctx context.Context, id int64) error
	DeleteUserConsentState(ctx context.Context, userIDHash []byte) error
	GetAdsTxtEntry(ctx context.Context, id int64) (AdsTxtEntry, error)
	GetAllActiveCampaignsWithStats(ctx context.Context) ([]GetAllActiveCampaignsWithStatsRow, error)
	GetAllBlacklist(ctx context.Context) ([]GetAllBlacklistRow, error)
	GetAllSystemSettings(ctx context.Context) ([]GetAllSystemSettingsRow, error)
	GetBrand(ctx context.Context, id pgtype.UUID) (AdvertiserBrand, error)
	GetBrandCreative(ctx context.Context, id pgtype.UUID) (BrandCreative, error)
	GetBrandForUpdate(ctx context.Context, id pgtype.UUID) (AdvertiserBrand, error)
	GetCampaign(ctx context.Context, id pgtype.UUID) (Campaign, error)
	GetCampaignBudget(ctx context.Context, id pgtype.UUID) (GetCampaignBudgetRow, error)
	GetCampaignForUpdate(ctx context.Context, id pgtype.UUID) (Campaign, error)
	GetCampaignFull(ctx context.Context, id pgtype.UUID) (Campaign, error)
	GetCampaignQuota(ctx context.Context, arg GetCampaignQuotaParams) (CampaignQuota, error)
	GetCampaignStats(ctx context.Context, campaignID pgtype.UUID) ([]CampaignStat, error)
	GetCampaignTemplate(ctx context.Context, id pgtype.UUID) (CampaignTemplate, error)
	GetCampaignsWithStats(ctx context.Context, customerID pgtype.UUID) ([]GetCampaignsWithStatsRow, error)
	GetCustomerByID(ctx context.Context, id pgtype.UUID) (Customer, error)
	GetCustomerForUpdate(ctx context.Context, id pgtype.UUID) (Customer, error)
	GetCustomerStats(ctx context.Context, customerIds []pgtype.UUID) ([]GetCustomerStatsRow, error)
	GetDrainingCampaignsForUpdate(ctx context.Context, arg GetDrainingCampaignsForUpdateParams) ([]Campaign, error)
	GetLedgerByHash(ctx context.Context, idempotencyHash pgtype.Text) (BalanceLedger, error)
	GetLedgerByHashForUpdate(ctx context.Context, idempotencyHash pgtype.Text) (BalanceLedger, error)
	GetLedgerByPaymentIntent(ctx context.Context, paymentIntentID pgtype.UUID) (BalanceLedger, error)
	GetLedgerByPaymentIntentForUpdate(ctx context.Context, paymentIntentID pgtype.UUID) (BalanceLedger, error)
	GetMaxDraftVersionWithMigrating(ctx context.Context) (int32, error)
	GetMaxSlotMapVersion(ctx context.Context) (int32, error)
	// Priority lane 0: safety-critical propagation (blacklist, pause, cancel) before bulk pacing/sync.
	GetPendingOutboxEventsForUpdate(ctx context.Context, limit int32) ([]OutboxEvent, error)
	GetPrivacyErasureRequest(ctx context.Context, id pgtype.UUID) (PrivacyErasureRequest, error)
	GetPrivacyErasureRequestForUpdate(ctx context.Context, id pgtype.UUID) (PrivacyErasureRequest, error)
	GetRtbDeal(ctx context.Context, id int64) (RtbDeal, error)
	GetRtbDealByDealID(ctx context.Context, dealID string) (RtbDeal, error)
	GetSeller(ctx context.Context, id int64) (Seller, error)
	GetSlotMapMeta(ctx context.Context) (GetSlotMapMetaRow, error)
	GetSlotMigration(ctx context.Context, arg GetSlotMigrationParams) (RedisSlotMigration, error)
	GetUserConsentState(ctx context.Context, userIDHash []byte) (UserConsentState, error)
	IncreaseCampaignQuotaReserved(ctx context.Context, arg IncreaseCampaignQuotaReservedParams) error
	InsertCampaignQuota(ctx context.Context, arg InsertCampaignQuotaParams) error
	// Consent (M6.1–M6.2)
	InsertConsentEvent(ctx context.Context, arg InsertConsentEventParams) error
	// Inserts a single event with ON CONFLICT for idempotency.
	// created_date is set explicitly for correct dedup within daily partitions.
	InsertEvent(ctx context.Context, arg InsertEventParams) error
	// Performs batch insert and atomically updates campaign stats.
	// Exactly-once aggregation is guaranteed because only newly inserted rows are counted.
	// Stats are attributed to the event's actual date (created_date), not CURRENT_DATE.
	// Invalid campaign_ids are filtered out before the stats insert to prevent FK violations
	// from rolling back the entire batch.
	InsertEventsBatch(ctx context.Context, arg InsertEventsBatchParams) error
	InsertReconDiscrepancy(ctx context.Context, arg InsertReconDiscrepancyParams) error
	InsertSlotMapRow(ctx context.Context, arg InsertSlotMapRowParams) error
	InsertSlotMigrationIfAbsent(ctx context.Context, arg InsertSlotMigrationIfAbsentParams) error
	ListActiveBrandCreatives(ctx context.Context, brandID pgtype.UUID) ([]BrandCreative, error)
	ListActiveCampaigns(ctx context.Context) ([]Campaign, error)
	ListAdsTxtEntries(ctx context.Context) ([]AdsTxtEntry, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AdminAuditLog, error)
	ListAuditLogsInRange(ctx context.Context, arg ListAuditLogsInRangeParams) ([]AdminAuditLog, error)
	ListAuditPaginated(ctx context.Context, arg ListAuditPaginatedParams) ([]AdminAuditLog, error)
	ListBlacklist(ctx context.Context, arg ListBlacklistParams) ([]IpBlacklist, error)
	ListBrandCreatives(ctx context.Context, brandID pgtype.UUID) ([]BrandCreative, error)
	ListBrandsByCustomer(ctx context.Context, customerID pgtype.UUID) ([]AdvertiserBrand, error)
	ListCampaignIDs(ctx context.Context) ([]pgtype.UUID, error)
	ListCampaignIDsByBrand(ctx context.Context, brandID pgtype.UUID) ([]pgtype.UUID, error)
	ListCampaignTemplates(ctx context.Context, arg ListCampaignTemplatesParams) ([]CampaignTemplate, error)
	ListCampaigns(ctx context.Context, arg ListCampaignsParams) ([]Campaign, error)
	ListCustomerLedger(ctx context.Context, arg ListCustomerLedgerParams) ([]BalanceLedger, error)
	ListCustomerLedgerByIDDesc(ctx context.Context, customerID pgtype.UUID) ([]BalanceLedger, error)
	ListCustomerLedgerExport(ctx context.Context, arg ListCustomerLedgerExportParams) ([]BalanceLedger, error)
	ListCustomers(ctx context.Context, arg ListCustomersParams) ([]Customer, error)
	ListCustomersForScoring(ctx context.Context) ([]ListCustomersForScoringRow, error)
	ListDistinctBrandsWithActiveCreatives(ctx context.Context) ([]pgtype.UUID, error)
	ListDrainingSlotMigrations(ctx context.Context) ([]RedisSlotMigration, error)
	ListExpiredBlacklistIPs(ctx context.Context, limit int32) ([]ListExpiredBlacklistIPsRow, error)
	ListLedgerChargebackEntryIDs(ctx context.Context, paymentIntentID pgtype.UUID) ([]int64, error)
	ListManagementReconRuns(ctx context.Context, arg ListManagementReconRunsParams) ([]ReconRun, error)
	ListMigratingSlotsByVersion(ctx context.Context, version int32) ([]RedisSlotMap, error)
	ListPrivacyErasureRequestsByStatus(ctx context.Context, arg ListPrivacyErasureRequestsByStatusParams) ([]PrivacyErasureRequest, error)
	ListRtbDeals(ctx context.Context) ([]RtbDeal, error)
	ListScheduledCampaigns(ctx context.Context, limit int32) ([]Campaign, error)
	ListSellers(ctx context.Context) ([]Seller, error)
	ListSlotMapByVersion(ctx context.Context, version int32) ([]RedisSlotMap, error)
	ListSlotMigrationsByState(ctx context.Context, dollar_1 []RedisSlotMigrationState) ([]RedisSlotMigration, error)
	ListSlotMigrationsByVersion(ctx context.Context, version int32) ([]RedisSlotMigration, error)
	ListStatusHistory(ctx context.Context, arg ListStatusHistoryParams) ([]CampaignStatusHistory, error)
	// quota.sql: sqlc queries for Distributed Quotas Postgres control plane (Phase 1.1).
	// ReserveChunk orchestration lives in QuotaRepo (transaction + sync_idempotency);
	// these queries provide row locks and DML primitives.
	LockCampaignBudgetForQuota(ctx context.Context, id pgtype.UUID) (LockCampaignBudgetForQuotaRow, error)
	LockCampaignQuota(ctx context.Context, arg LockCampaignQuotaParams) (CampaignQuota, error)
	LockSlotMapEntry(ctx context.Context, arg LockSlotMapEntryParams) (RedisSlotMap, error)
	LockSlotMapMeta(ctx context.Context) (LockSlotMapMetaRow, error)
	MarkOutboxEventProcessed(ctx context.Context, id int64) error
	MaxCustomerReconLagMicro(ctx context.Context, customerID pgtype.UUID) (int64, error)
	PauseCampaign(ctx context.Context, id pgtype.UUID) (Campaign, error)
	ResumeCampaign(ctx context.Context, id pgtype.UUID) (Campaign, error)
	SetSlotMapActiveVersion(ctx context.Context, activeVersion int32) error
	SetSystemSetting(ctx context.Context, arg SetSystemSettingParams) error
	SoftDeleteCampaign(ctx context.Context, id pgtype.UUID) error
	SumCampaignReservedByCampaign(ctx context.Context, campaignID pgtype.UUID) (int64, error)
	SumCampaignStatsInRange(ctx context.Context, arg SumCampaignStatsInRangeParams) (SumCampaignStatsInRangeRow, error)
	// Recon queries (financial integrity cold path)
	// These queries power the background reconciliation worker. They are intentionally
	// scoped to closed time windows to eliminate races with the hot SyncWorker path.
	SumLedgerSpendByCampaignWindow(ctx context.Context, arg SumLedgerSpendByCampaignWindowParams) ([]SumLedgerSpendByCampaignWindowRow, error)
	SumPaymentChargebackAmountForIntent(ctx context.Context, paymentIntentID pgtype.UUID) (int64, error)
	SumPaymentChargebackReversalAmountForIntent(ctx context.Context, paymentIntentID pgtype.UUID) (int64, error)
	SumPaymentRefundAmountForIntent(ctx context.Context, paymentIntentID pgtype.UUID) (int64, error)
	UpdateAdsTxtEntry(ctx context.Context, arg UpdateAdsTxtEntryParams) (AdsTxtEntry, error)
	UpdateBrandCreative(ctx context.Context, arg UpdateBrandCreativeParams) (BrandCreative, error)
	UpdateCampaignBudget(ctx context.Context, arg UpdateCampaignBudgetParams) (Campaign, error)
	// Campaign consent requirements (M6.3)
	UpdateCampaignConsentPurposes(ctx context.Context, arg UpdateCampaignConsentPurposesParams) (Campaign, error)
	UpdateCampaignFraudConfig(ctx context.Context, arg UpdateCampaignFraudConfigParams) (Campaign, error)
	UpdateCampaignPacing(ctx context.Context, arg UpdateCampaignPacingParams) (Campaign, error)
	// Campaign schedule / lifecycle
	UpdateCampaignSchedule(ctx context.Context, arg UpdateCampaignScheduleParams) (Campaign, error)
	UpdateCampaignSpend(ctx context.Context, arg UpdateCampaignSpendParams) error
	UpdateCampaignStats(ctx context.Context, arg UpdateCampaignStatsParams) error
	UpdateCampaignStatsBatch(ctx context.Context, arg UpdateCampaignStatsBatchParams) error
	UpdateCampaignStatus(ctx context.Context, arg UpdateCampaignStatusParams) (Campaign, error)
	UpdateCampaignSupplyChain(ctx context.Context, arg UpdateCampaignSupplyChainParams) (Campaign, error)
	UpdateCustomerBalance(ctx context.Context, arg UpdateCustomerBalanceParams) error
	UpdateCustomerBalanceManagement(ctx context.Context, arg UpdateCustomerBalanceManagementParams) (Customer, error)
	UpdateCustomerOverdraft(ctx context.Context, arg UpdateCustomerOverdraftParams) (Customer, error)
	UpdatePrivacyErasureStatus(ctx context.Context, arg UpdatePrivacyErasureStatusParams) error
	UpdateReconRun(ctx context.Context, arg UpdateReconRunParams) error
	UpdateRtbDeal(ctx context.Context, arg UpdateRtbDealParams) (RtbDeal, error)
	UpdateSeller(ctx context.Context, arg UpdateSellerParams) (Seller, error)
	UpdateSlotMapEntry(ctx context.Context, arg UpdateSlotMapEntryParams) error
	UpdateSlotMigrationProgress(ctx context.Context, arg UpdateSlotMigrationProgressParams) error
	UpdateSlotMigrationState(ctx context.Context, arg UpdateSlotMigrationStateParams) error
	UpsertSlotMigration(ctx context.Context, arg UpsertSlotMigrationParams) error
	UpsertUserConsentState(ctx context.Context, arg UpsertUserConsentStateParams) error
}

var _ Querier = (*Queries)(nil)
