// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: slot_map.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const copySlotMapVersion = `-- name: CopySlotMapVersion :exec
INSERT INTO redis_slot_map (version, slot, shard_id, state)
SELECT $2, src.slot, src.shard_id, src.state
FROM redis_slot_map AS src
WHERE src.version = $1
`

type CopySlotMapVersionParams struct {
	Version   int32 `json:"version"`
	Version_2 int32 `json:"version_2"`
}

func (q *Queries) CopySlotMapVersion(ctx context.Context, arg CopySlotMapVersionParams) error {
	_, err := q.db.Exec(ctx, copySlotMapVersion, arg.Version, arg.Version_2)
	return err
}

const countSlotMapRowsForVersion = `-- name: CountSlotMapRowsForVersion :one
SELECT COUNT(*)::INT AS row_count
FROM redis_slot_map
WHERE version = $1
`

func (q *Queries) CountSlotMapRowsForVersion(ctx context.Context, version int32) (int32, error) {
	row := q.db.QueryRow(ctx, countSlotMapRowsForVersion, version)
	var row_count int32
	err := row.Scan(&row_count)
	return row_count, err
}

const getMaxSlotMapVersion = `-- name: GetMaxSlotMapVersion :one
SELECT COALESCE(MAX(version), 0)::INT AS max_version
FROM redis_slot_map
`

func (q *Queries) GetMaxSlotMapVersion(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, getMaxSlotMapVersion)
	var max_version int32
	err := row.Scan(&max_version)
	return max_version, err
}

const getSlotMapMeta = `-- name: GetSlotMapMeta :one
SELECT active_version, updated_at
FROM redis_slot_map_meta
WHERE id = 1
`

type GetSlotMapMetaRow struct {
	ActiveVersion int32              `json:"active_version"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetSlotMapMeta(ctx context.Context) (GetSlotMapMetaRow, error) {
	row := q.db.QueryRow(ctx, getSlotMapMeta)
	var i GetSlotMapMetaRow
	err := row.Scan(&i.ActiveVersion, &i.UpdatedAt)
	return i, err
}

const insertSlotMapRow = `-- name: InsertSlotMapRow :exec
INSERT INTO redis_slot_map (version, slot, shard_id, state)
VALUES ($1, $2, $3, $4)
`

type InsertSlotMapRowParams struct {
	Version int32          `json:"version"`
	Slot    int16          `json:"slot"`
	ShardID int16          `json:"shard_id"`
	State   RedisSlotState `json:"state"`
}

func (q *Queries) InsertSlotMapRow(ctx context.Context, arg InsertSlotMapRowParams) error {
	_, err := q.db.Exec(ctx, insertSlotMapRow,
		arg.Version,
		arg.Slot,
		arg.ShardID,
		arg.State,
	)
	return err
}

const listMigratingSlotsByVersion = `-- name: ListMigratingSlotsByVersion :many
SELECT version, slot, shard_id, state, updated_at
FROM redis_slot_map
WHERE version = $1 AND state = 'MIGRATING'
ORDER BY slot ASC
`

func (q *Queries) ListMigratingSlotsByVersion(ctx context.Context, version int32) ([]RedisSlotMap, error) {
	rows, err := q.db.Query(ctx, listMigratingSlotsByVersion, version)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RedisSlotMap
	for rows.Next() {
		var i RedisSlotMap
		if err := rows.Scan(
			&i.Version,
			&i.Slot,
			&i.ShardID,
			&i.State,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSlotMapByVersion = `-- name: ListSlotMapByVersion :many
SELECT version, slot, shard_id, state, updated_at
FROM redis_slot_map
WHERE version = $1
ORDER BY slot ASC
`

func (q *Queries) ListSlotMapByVersion(ctx context.Context, version int32) ([]RedisSlotMap, error) {
	rows, err := q.db.Query(ctx, listSlotMapByVersion, version)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RedisSlotMap
	for rows.Next() {
		var i RedisSlotMap
		if err := rows.Scan(
			&i.Version,
			&i.Slot,
			&i.ShardID,
			&i.State,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSlotMapEntry = `-- name: LockSlotMapEntry :one
SELECT version, slot, shard_id, state, updated_at
FROM redis_slot_map
WHERE version = $1 AND slot = $2
FOR UPDATE
`

type LockSlotMapEntryParams struct {
	Version int32 `json:"version"`
	Slot    int16 `json:"slot"`
}

func (q *Queries) LockSlotMapEntry(ctx context.Context, arg LockSlotMapEntryParams) (RedisSlotMap, error) {
	row := q.db.QueryRow(ctx, lockSlotMapEntry, arg.Version, arg.Slot)
	var i RedisSlotMap
	err := row.Scan(
		&i.Version,
		&i.Slot,
		&i.ShardID,
		&i.State,
		&i.UpdatedAt,
	)
	return i, err
}

const lockSlotMapMeta = `-- name: LockSlotMapMeta :one
SELECT active_version, updated_at
FROM redis_slot_map_meta
WHERE id = 1
FOR UPDATE
`

type LockSlotMapMetaRow struct {
	ActiveVersion int32              `json:"active_version"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) LockSlotMapMeta(ctx context.Context) (LockSlotMapMetaRow, error) {
	row := q.db.QueryRow(ctx, lockSlotMapMeta)
	var i LockSlotMapMetaRow
	err := row.Scan(&i.ActiveVersion, &i.UpdatedAt)
	return i, err
}

const setSlotMapActiveVersion = `-- name: SetSlotMapActiveVersion :exec
UPDATE redis_slot_map_meta
SET active_version = $1,
    updated_at = NOW()
WHERE id = 1
`

func (q *Queries) SetSlotMapActiveVersion(ctx context.Context, activeVersion int32) error {
	_, err := q.db.Exec(ctx, setSlotMapActiveVersion, activeVersion)
	return err
}

const updateSlotMapEntry = `-- name: UpdateSlotMapEntry :exec
UPDATE redis_slot_map
SET shard_id = $3,
    state = $4,
    updated_at = NOW()
WHERE version = $1 AND slot = $2
`

type UpdateSlotMapEntryParams struct {
	Version int32          `json:"version"`
	Slot    int16          `json:"slot"`
	ShardID int16          `json:"shard_id"`
	State   RedisSlotState `json:"state"`
}

func (q *Queries) UpdateSlotMapEntry(ctx context.Context, arg UpdateSlotMapEntryParams) error {
	_, err := q.db.Exec(ctx, updateSlotMapEntry,
		arg.Version,
		arg.Slot,
		arg.ShardID,
		arg.State,
	)
	return err
}
