// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: payment.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentIntentStatus int32

const (
	PaymentIntentStatus_PAYMENT_INTENT_STATUS_UNSPECIFIED       PaymentIntentStatus = 0
	PaymentIntentStatus_PAYMENT_INTENT_STATUS_CREATED           PaymentIntentStatus = 1
	PaymentIntentStatus_PAYMENT_INTENT_STATUS_PENDING_PROVIDER  PaymentIntentStatus = 2
	PaymentIntentStatus_PAYMENT_INTENT_STATUS_PROCESSING        PaymentIntentStatus = 3
	PaymentIntentStatus_PAYMENT_INTENT_STATUS_SUCCEEDED         PaymentIntentStatus = 4
	PaymentIntentStatus_PAYMENT_INTENT_STATUS_FAILED            PaymentIntentStatus = 5
	PaymentIntentStatus_PAYMENT_INTENT_STATUS_CANCELLED         PaymentIntentStatus = 6
	PaymentIntentStatus_PAYMENT_INTENT_STATUS_REFUNDED          PaymentIntentStatus = 7
	PaymentIntentStatus_PAYMENT_INTENT_STATUS_SETTLEMENT_FAILED PaymentIntentStatus = 8
)

// Enum value maps for PaymentIntentStatus.
var (
	PaymentIntentStatus_name = map[int32]string{
		0: "PAYMENT_INTENT_STATUS_UNSPECIFIED",
		1: "PAYMENT_INTENT_STATUS_CREATED",
		2: "PAYMENT_INTENT_STATUS_PENDING_PROVIDER",
		3: "PAYMENT_INTENT_STATUS_PROCESSING",
		4: "PAYMENT_INTENT_STATUS_SUCCEEDED",
		5: "PAYMENT_INTENT_STATUS_FAILED",
		6: "PAYMENT_INTENT_STATUS_CANCELLED",
		7: "PAYMENT_INTENT_STATUS_REFUNDED",
		8: "PAYMENT_INTENT_STATUS_SETTLEMENT_FAILED",
	}
	PaymentIntentStatus_value = map[string]int32{
		"PAYMENT_INTENT_STATUS_UNSPECIFIED":       0,
		"PAYMENT_INTENT_STATUS_CREATED":           1,
		"PAYMENT_INTENT_STATUS_PENDING_PROVIDER":  2,
		"PAYMENT_INTENT_STATUS_PROCESSING":        3,
		"PAYMENT_INTENT_STATUS_SUCCEEDED":         4,
		"PAYMENT_INTENT_STATUS_FAILED":            5,
		"PAYMENT_INTENT_STATUS_CANCELLED":         6,
		"PAYMENT_INTENT_STATUS_REFUNDED":          7,
		"PAYMENT_INTENT_STATUS_SETTLEMENT_FAILED": 8,
	}
)

func (x PaymentIntentStatus) Enum() *PaymentIntentStatus {
	p := new(PaymentIntentStatus)
	*p = x
	return p
}

func (x PaymentIntentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentIntentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_payment_proto_enumTypes[0].Descriptor()
}

func (PaymentIntentStatus) Type() protoreflect.EnumType {
	return &file_payment_proto_enumTypes[0]
}

func (x PaymentIntentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentIntentStatus.Descriptor instead.
func (PaymentIntentStatus) EnumDescriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{0}
}

type CreatePaymentIntentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CustomerId     string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`             // UUID, references ads.customers (no FK)
	AmountMicro    int64                  `protobuf:"varint,2,opt,name=amount_micro,json=amountMicro,proto3" json:"amount_micro,omitempty"`         // > 0, 10^6 scale (matches ledger)
	Currency       string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`                                   // ISO 4217, default "USD"
	IdempotencyKey string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"` // required, client-supplied (HTMX: Idempotency-Key header)
	Metadata       map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreatePaymentIntentRequest) Reset() {
	*x = CreatePaymentIntentRequest{}
	mi := &file_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentIntentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentIntentRequest) ProtoMessage() {}

func (x *CreatePaymentIntentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentIntentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentIntentRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePaymentIntentRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CreatePaymentIntentRequest) GetAmountMicro() int64 {
	if x != nil {
		return x.AmountMicro
	}
	return 0
}

func (x *CreatePaymentIntentRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreatePaymentIntentRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *CreatePaymentIntentRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CreatePaymentIntentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IntentId      string                 `protobuf:"bytes,1,opt,name=intent_id,json=intentId,proto3" json:"intent_id,omitempty"`
	Status        PaymentIntentStatus    `protobuf:"varint,2,opt,name=status,proto3,enum=payment.PaymentIntentStatus" json:"status,omitempty"`
	CheckoutUrl   string                 `protobuf:"bytes,3,opt,name=checkout_url,json=checkoutUrl,proto3" json:"checkout_url,omitempty"` // empty until Stripe connected
	ProviderRef   string                 `protobuf:"bytes,4,opt,name=provider_ref,json=providerRef,proto3" json:"provider_ref,omitempty"` // pi_xxx / cs_xxx when set
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentIntentResponse) Reset() {
	*x = CreatePaymentIntentResponse{}
	mi := &file_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentIntentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentIntentResponse) ProtoMessage() {}

func (x *CreatePaymentIntentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentIntentResponse.ProtoReflect.Descriptor instead.
func (*CreatePaymentIntentResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePaymentIntentResponse) GetIntentId() string {
	if x != nil {
		return x.IntentId
	}
	return ""
}

func (x *CreatePaymentIntentResponse) GetStatus() PaymentIntentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentIntentStatus_PAYMENT_INTENT_STATUS_UNSPECIFIED
}

func (x *CreatePaymentIntentResponse) GetCheckoutUrl() string {
	if x != nil {
		return x.CheckoutUrl
	}
	return ""
}

func (x *CreatePaymentIntentResponse) GetProviderRef() string {
	if x != nil {
		return x.ProviderRef
	}
	return ""
}

type GetPaymentIntentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IntentId      string                 `protobuf:"bytes,1,opt,name=intent_id,json=intentId,proto3" json:"intent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentIntentRequest) Reset() {
	*x = GetPaymentIntentRequest{}
	mi := &file_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentIntentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentIntentRequest) ProtoMessage() {}

func (x *GetPaymentIntentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentIntentRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentIntentRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{2}
}

func (x *GetPaymentIntentRequest) GetIntentId() string {
	if x != nil {
		return x.IntentId
	}
	return ""
}

type ListPaymentIntentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPaymentIntentsRequest) Reset() {
	*x = ListPaymentIntentsRequest{}
	mi := &file_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentIntentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentIntentsRequest) ProtoMessage() {}

func (x *ListPaymentIntentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentIntentsRequest.ProtoReflect.Descriptor instead.
func (*ListPaymentIntentsRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{3}
}

func (x *ListPaymentIntentsRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *ListPaymentIntentsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListPaymentIntentsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListPaymentIntentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Intents       []*PaymentIntent       `protobuf:"bytes,1,rep,name=intents,proto3" json:"intents,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPaymentIntentsResponse) Reset() {
	*x = ListPaymentIntentsResponse{}
	mi := &file_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentIntentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentIntentsResponse) ProtoMessage() {}

func (x *ListPaymentIntentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentIntentsResponse.ProtoReflect.Descriptor instead.
func (*ListPaymentIntentsResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{4}
}

func (x *ListPaymentIntentsResponse) GetIntents() []*PaymentIntent {
	if x != nil {
		return x.Intents
	}
	return nil
}

func (x *ListPaymentIntentsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type PaymentIntent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId     string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	AmountMicro    int64                  `protobuf:"varint,3,opt,name=amount_micro,json=amountMicro,proto3" json:"amount_micro,omitempty"`
	Currency       string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Status         PaymentIntentStatus    `protobuf:"varint,5,opt,name=status,proto3,enum=payment.PaymentIntentStatus" json:"status,omitempty"`
	Provider       string                 `protobuf:"bytes,6,opt,name=provider,proto3" json:"provider,omitempty"`
	ProviderRef    string                 `protobuf:"bytes,7,opt,name=provider_ref,json=providerRef,proto3" json:"provider_ref,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,8,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PaymentIntent) Reset() {
	*x = PaymentIntent{}
	mi := &file_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentIntent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentIntent) ProtoMessage() {}

func (x *PaymentIntent) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentIntent.ProtoReflect.Descriptor instead.
func (*PaymentIntent) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{5}
}

func (x *PaymentIntent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PaymentIntent) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *PaymentIntent) GetAmountMicro() int64 {
	if x != nil {
		return x.AmountMicro
	}
	return 0
}

func (x *PaymentIntent) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *PaymentIntent) GetStatus() PaymentIntentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentIntentStatus_PAYMENT_INTENT_STATUS_UNSPECIFIED
}

func (x *PaymentIntent) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *PaymentIntent) GetProviderRef() string {
	if x != nil {
		return x.ProviderRef
	}
	return ""
}

func (x *PaymentIntent) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *PaymentIntent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PaymentIntent) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_payment_proto protoreflect.FileDescriptor

const file_payment_proto_rawDesc = "" +
	"\n" +
	"\rpayment.proto\x12\apayment\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb1\x02\n" +
	"\x1aCreatePaymentIntentRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12!\n" +
	"\famount_micro\x18\x02 \x01(\x03R\vamountMicro\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\x12M\n" +
	"\bmetadata\x18\x05 \x03(\v21.payment.CreatePaymentIntentRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb6\x01\n" +
	"\x1bCreatePaymentIntentResponse\x12\x1b\n" +
	"\tintent_id\x18\x01 \x01(\tR\bintentId\x124\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1c.payment.PaymentIntentStatusR\x06status\x12!\n" +
	"\fcheckout_url\x18\x03 \x01(\tR\vcheckoutUrl\x12!\n" +
	"\fprovider_ref\x18\x04 \x01(\tR\vproviderRef\"6\n" +
	"\x17GetPaymentIntentRequest\x12\x1b\n" +
	"\tintent_id\x18\x01 \x01(\tR\bintentId\"j\n" +
	"\x19ListPaymentIntentsRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"d\n" +
	"\x1aListPaymentIntentsResponse\x120\n" +
	"\aintents\x18\x01 \x03(\v2\x16.payment.PaymentIntentR\aintents\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\x93\x03\n" +
	"\rPaymentIntent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12!\n" +
	"\famount_micro\x18\x03 \x01(\x03R\vamountMicro\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x124\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1c.payment.PaymentIntentStatusR\x06status\x12\x1a\n" +
	"\bprovider\x18\x06 \x01(\tR\bprovider\x12!\n" +
	"\fprovider_ref\x18\a \x01(\tR\vproviderRef\x12'\n" +
	"\x0fidempotency_key\x18\b \x01(\tR\x0eidempotencyKey\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt*\xee\x02\n" +
	"\x13PaymentIntentStatus\x12%\n" +
	"!PAYMENT_INTENT_STATUS_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dPAYMENT_INTENT_STATUS_CREATED\x10\x01\x12*\n" +
	"&PAYMENT_INTENT_STATUS_PENDING_PROVIDER\x10\x02\x12$\n" +
	" PAYMENT_INTENT_STATUS_PROCESSING\x10\x03\x12#\n" +
	"\x1fPAYMENT_INTENT_STATUS_SUCCEEDED\x10\x04\x12 \n" +
	"\x1cPAYMENT_INTENT_STATUS_FAILED\x10\x05\x12#\n" +
	"\x1fPAYMENT_INTENT_STATUS_CANCELLED\x10\x06\x12\"\n" +
	"\x1ePAYMENT_INTENT_STATUS_REFUNDED\x10\a\x12+\n" +
	"'PAYMENT_INTENT_STATUS_SETTLEMENT_FAILED\x10\b2\x9f\x02\n" +
	"\x0ePaymentService\x12`\n" +
	"\x13CreatePaymentIntent\x12#.payment.CreatePaymentIntentRequest\x1a$.payment.CreatePaymentIntentResponse\x12L\n" +
	"\x10GetPaymentIntent\x12 .payment.GetPaymentIntentRequest\x1a\x16.payment.PaymentIntent\x12]\n" +
	"\x12ListPaymentIntents\x12\".payment.ListPaymentIntentsRequest\x1a#.payment.ListPaymentIntentsResponseB\x1dZ\x1bespx/internal/payment/pb;pbb\x06proto3"

var (
	file_payment_proto_rawDescOnce sync.Once
	file_payment_proto_rawDescData []byte
)

func file_payment_proto_rawDescGZIP() []byte {
	file_payment_proto_rawDescOnce.Do(func() {
		file_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)))
	})
	return file_payment_proto_rawDescData
}

var file_payment_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_payment_proto_goTypes = []any{
	(PaymentIntentStatus)(0),            // 0: payment.PaymentIntentStatus
	(*CreatePaymentIntentRequest)(nil),  // 1: payment.CreatePaymentIntentRequest
	(*CreatePaymentIntentResponse)(nil), // 2: payment.CreatePaymentIntentResponse
	(*GetPaymentIntentRequest)(nil),     // 3: payment.GetPaymentIntentRequest
	(*ListPaymentIntentsRequest)(nil),   // 4: payment.ListPaymentIntentsRequest
	(*ListPaymentIntentsResponse)(nil),  // 5: payment.ListPaymentIntentsResponse
	(*PaymentIntent)(nil),               // 6: payment.PaymentIntent
	nil,                                 // 7: payment.CreatePaymentIntentRequest.MetadataEntry
	(*timestamppb.Timestamp)(nil),       // 8: google.protobuf.Timestamp
}
var file_payment_proto_depIdxs = []int32{
	7, // 0: payment.CreatePaymentIntentRequest.metadata:type_name -> payment.CreatePaymentIntentRequest.MetadataEntry
	0, // 1: payment.CreatePaymentIntentResponse.status:type_name -> payment.PaymentIntentStatus
	6, // 2: payment.ListPaymentIntentsResponse.intents:type_name -> payment.PaymentIntent
	0, // 3: payment.PaymentIntent.status:type_name -> payment.PaymentIntentStatus
	8, // 4: payment.PaymentIntent.created_at:type_name -> google.protobuf.Timestamp
	8, // 5: payment.PaymentIntent.updated_at:type_name -> google.protobuf.Timestamp
	1, // 6: payment.PaymentService.CreatePaymentIntent:input_type -> payment.CreatePaymentIntentRequest
	3, // 7: payment.PaymentService.GetPaymentIntent:input_type -> payment.GetPaymentIntentRequest
	4, // 8: payment.PaymentService.ListPaymentIntents:input_type -> payment.ListPaymentIntentsRequest
	2, // 9: payment.PaymentService.CreatePaymentIntent:output_type -> payment.CreatePaymentIntentResponse
	6, // 10: payment.PaymentService.GetPaymentIntent:output_type -> payment.PaymentIntent
	5, // 11: payment.PaymentService.ListPaymentIntents:output_type -> payment.ListPaymentIntentsResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_payment_proto_init() }
func file_payment_proto_init() {
	if File_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_proto_goTypes,
		DependencyIndexes: file_payment_proto_depIdxs,
		EnumInfos:         file_payment_proto_enumTypes,
		MessageInfos:      file_payment_proto_msgTypes,
	}.Build()
	File_payment_proto = out.File
	file_payment_proto_goTypes = nil
	file_payment_proto_depIdxs = nil
}
