// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func ContentsNav() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"contents-nav\"><button type=\"button\" class=\"btn contents-nav__trigger\" aria-controls=\"contents-panel\" aria-expanded=\"false\">Contents</button><div id=\"contents-panel\" class=\"contents-nav__panel\" role=\"region\" aria-label=\"Table of contents\"><table><tbody><tr><th scope=\"row\"><a class=\"link-primary\" href=\"#business\">Business</a></th><td>Prepaid ledger, audit trail, cancel settlement</td></tr><tr><th scope=\"row\"><a class=\"link-primary\" href=\"#architecture\">Architecture &amp; stack</a></th><td>Ingest, engine, telemetry pipeline, SSR admin UI</td></tr><tr><th scope=\"row\"><a class=\"link-primary\" href=\"#storage\">Storage</a></th><td>PostgreSQL, ClickHouse, Redis — data ownership</td></tr><tr><th scope=\"row\"><a class=\"link-primary\" href=\"#roles\">Access</a></th><td>SA / M / C / G permission matrix</td></tr><tr><th scope=\"row\"><a class=\"link-primary\" href=\"#lifecycle\">Campaign lifecycle</a></th><td>Status transitions, cancel drain, ledger effects</td></tr><tr><th scope=\"row\"><a class=\"link-primary\" href=\"#deployment\">Deployment</a></th><td>Host topology, ports, service boundaries</td></tr><tr><th scope=\"row\"><a class=\"link-primary\" href=\"#failures\">Failure modes</a></th><td>Breaker, shard loss, CH lag, outbox stall</td></tr><tr><th scope=\"row\"><a class=\"link-primary\" href=\"#metrics\">Performance</a></th><td>1M+ RPS, p99 bid latency, telemetry flush</td></tr></tbody></table></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
