// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: billing.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateInvoiceRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	CustomerId string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	// billing_month is the first day of the month (UTC), e.g. 2026-06-01.
	BillingMonth  *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=billing_month,json=billingMonth,proto3" json:"billing_month,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateInvoiceRequest) Reset() {
	*x = GenerateInvoiceRequest{}
	mi := &file_billing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateInvoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateInvoiceRequest) ProtoMessage() {}

func (x *GenerateInvoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateInvoiceRequest.ProtoReflect.Descriptor instead.
func (*GenerateInvoiceRequest) Descriptor() ([]byte, []int) {
	return file_billing_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateInvoiceRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *GenerateInvoiceRequest) GetBillingMonth() *timestamppb.Timestamp {
	if x != nil {
		return x.BillingMonth
	}
	return nil
}

type GetInvoiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvoiceId     string                 `protobuf:"bytes,1,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInvoiceRequest) Reset() {
	*x = GetInvoiceRequest{}
	mi := &file_billing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInvoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvoiceRequest) ProtoMessage() {}

func (x *GetInvoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInvoiceRequest.ProtoReflect.Descriptor instead.
func (*GetInvoiceRequest) Descriptor() ([]byte, []int) {
	return file_billing_proto_rawDescGZIP(), []int{1}
}

func (x *GetInvoiceRequest) GetInvoiceId() string {
	if x != nil {
		return x.InvoiceId
	}
	return ""
}

type ListInvoicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInvoicesRequest) Reset() {
	*x = ListInvoicesRequest{}
	mi := &file_billing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInvoicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInvoicesRequest) ProtoMessage() {}

func (x *ListInvoicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInvoicesRequest.ProtoReflect.Descriptor instead.
func (*ListInvoicesRequest) Descriptor() ([]byte, []int) {
	return file_billing_proto_rawDescGZIP(), []int{2}
}

func (x *ListInvoicesRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *ListInvoicesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListInvoicesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListInvoicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invoices      []*Invoice             `protobuf:"bytes,1,rep,name=invoices,proto3" json:"invoices,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInvoicesResponse) Reset() {
	*x = ListInvoicesResponse{}
	mi := &file_billing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInvoicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInvoicesResponse) ProtoMessage() {}

func (x *ListInvoicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInvoicesResponse.ProtoReflect.Descriptor instead.
func (*ListInvoicesResponse) Descriptor() ([]byte, []int) {
	return file_billing_proto_rawDescGZIP(), []int{3}
}

func (x *ListInvoicesResponse) GetInvoices() []*Invoice {
	if x != nil {
		return x.Invoices
	}
	return nil
}

func (x *ListInvoicesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type InvoiceLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LedgerType    string                 `protobuf:"bytes,1,opt,name=ledger_type,json=ledgerType,proto3" json:"ledger_type,omitempty"`
	AmountMicro   int64                  `protobuf:"varint,2,opt,name=amount_micro,json=amountMicro,proto3" json:"amount_micro,omitempty"`
	EntryCount    int32                  `protobuf:"varint,3,opt,name=entry_count,json=entryCount,proto3" json:"entry_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvoiceLine) Reset() {
	*x = InvoiceLine{}
	mi := &file_billing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvoiceLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvoiceLine) ProtoMessage() {}

func (x *InvoiceLine) ProtoReflect() protoreflect.Message {
	mi := &file_billing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvoiceLine.ProtoReflect.Descriptor instead.
func (*InvoiceLine) Descriptor() ([]byte, []int) {
	return file_billing_proto_rawDescGZIP(), []int{4}
}

func (x *InvoiceLine) GetLedgerType() string {
	if x != nil {
		return x.LedgerType
	}
	return ""
}

func (x *InvoiceLine) GetAmountMicro() int64 {
	if x != nil {
		return x.AmountMicro
	}
	return 0
}

func (x *InvoiceLine) GetEntryCount() int32 {
	if x != nil {
		return x.EntryCount
	}
	return 0
}

type Invoice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	BillingMonth  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=billing_month,json=billingMonth,proto3" json:"billing_month,omitempty"`
	SubtotalMicro int64                  `protobuf:"varint,4,opt,name=subtotal_micro,json=subtotalMicro,proto3" json:"subtotal_micro,omitempty"`
	TaxMicro      int64                  `protobuf:"varint,5,opt,name=tax_micro,json=taxMicro,proto3" json:"tax_micro,omitempty"`
	TotalMicro    int64                  `protobuf:"varint,6,opt,name=total_micro,json=totalMicro,proto3" json:"total_micro,omitempty"`
	Currency      string                 `protobuf:"bytes,7,opt,name=currency,proto3" json:"currency,omitempty"`
	TaxScheme     string                 `protobuf:"bytes,8,opt,name=tax_scheme,json=taxScheme,proto3" json:"tax_scheme,omitempty"`
	TaxRateBps    int32                  `protobuf:"varint,9,opt,name=tax_rate_bps,json=taxRateBps,proto3" json:"tax_rate_bps,omitempty"`
	Lines         []*InvoiceLine         `protobuf:"bytes,10,rep,name=lines,proto3" json:"lines,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Invoice) Reset() {
	*x = Invoice{}
	mi := &file_billing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Invoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invoice) ProtoMessage() {}

func (x *Invoice) ProtoReflect() protoreflect.Message {
	mi := &file_billing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invoice.ProtoReflect.Descriptor instead.
func (*Invoice) Descriptor() ([]byte, []int) {
	return file_billing_proto_rawDescGZIP(), []int{5}
}

func (x *Invoice) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Invoice) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *Invoice) GetBillingMonth() *timestamppb.Timestamp {
	if x != nil {
		return x.BillingMonth
	}
	return nil
}

func (x *Invoice) GetSubtotalMicro() int64 {
	if x != nil {
		return x.SubtotalMicro
	}
	return 0
}

func (x *Invoice) GetTaxMicro() int64 {
	if x != nil {
		return x.TaxMicro
	}
	return 0
}

func (x *Invoice) GetTotalMicro() int64 {
	if x != nil {
		return x.TotalMicro
	}
	return 0
}

func (x *Invoice) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Invoice) GetTaxScheme() string {
	if x != nil {
		return x.TaxScheme
	}
	return ""
}

func (x *Invoice) GetTaxRateBps() int32 {
	if x != nil {
		return x.TaxRateBps
	}
	return 0
}

func (x *Invoice) GetLines() []*InvoiceLine {
	if x != nil {
		return x.Lines
	}
	return nil
}

func (x *Invoice) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_billing_proto protoreflect.FileDescriptor

const file_billing_proto_rawDesc = "" +
	"\n" +
	"\rbilling.proto\x12\abilling\x1a\x1fgoogle/protobuf/timestamp.proto\"z\n" +
	"\x16GenerateInvoiceRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12?\n" +
	"\rbilling_month\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\fbillingMonth\"2\n" +
	"\x11GetInvoiceRequest\x12\x1d\n" +
	"\n" +
	"invoice_id\x18\x01 \x01(\tR\tinvoiceId\"d\n" +
	"\x13ListInvoicesRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"Z\n" +
	"\x14ListInvoicesResponse\x12,\n" +
	"\binvoices\x18\x01 \x03(\v2\x10.billing.InvoiceR\binvoices\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"r\n" +
	"\vInvoiceLine\x12\x1f\n" +
	"\vledger_type\x18\x01 \x01(\tR\n" +
	"ledgerType\x12!\n" +
	"\famount_micro\x18\x02 \x01(\x03R\vamountMicro\x12\x1f\n" +
	"\ventry_count\x18\x03 \x01(\x05R\n" +
	"entryCount\"\xa4\x03\n" +
	"\aInvoice\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12?\n" +
	"\rbilling_month\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\fbillingMonth\x12%\n" +
	"\x0esubtotal_micro\x18\x04 \x01(\x03R\rsubtotalMicro\x12\x1b\n" +
	"\ttax_micro\x18\x05 \x01(\x03R\btaxMicro\x12\x1f\n" +
	"\vtotal_micro\x18\x06 \x01(\x03R\n" +
	"totalMicro\x12\x1a\n" +
	"\bcurrency\x18\a \x01(\tR\bcurrency\x12\x1d\n" +
	"\n" +
	"tax_scheme\x18\b \x01(\tR\ttaxScheme\x12 \n" +
	"\ftax_rate_bps\x18\t \x01(\x05R\n" +
	"taxRateBps\x12*\n" +
	"\x05lines\x18\n" +
	" \x03(\v2\x14.billing.InvoiceLineR\x05lines\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt2\xdf\x01\n" +
	"\x0eBillingService\x12D\n" +
	"\x0fGenerateInvoice\x12\x1f.billing.GenerateInvoiceRequest\x1a\x10.billing.Invoice\x12:\n" +
	"\n" +
	"GetInvoice\x12\x1a.billing.GetInvoiceRequest\x1a\x10.billing.Invoice\x12K\n" +
	"\fListInvoices\x12\x1c.billing.ListInvoicesRequest\x1a\x1d.billing.ListInvoicesResponseB\x1dZ\x1bespx/internal/billing/pb;pbb\x06proto3"

var (
	file_billing_proto_rawDescOnce sync.Once
	file_billing_proto_rawDescData []byte
)

func file_billing_proto_rawDescGZIP() []byte {
	file_billing_proto_rawDescOnce.Do(func() {
		file_billing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_billing_proto_rawDesc), len(file_billing_proto_rawDesc)))
	})
	return file_billing_proto_rawDescData
}

var file_billing_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_billing_proto_goTypes = []any{
	(*GenerateInvoiceRequest)(nil), // 0: billing.GenerateInvoiceRequest
	(*GetInvoiceRequest)(nil),      // 1: billing.GetInvoiceRequest
	(*ListInvoicesRequest)(nil),    // 2: billing.ListInvoicesRequest
	(*ListInvoicesResponse)(nil),   // 3: billing.ListInvoicesResponse
	(*InvoiceLine)(nil),            // 4: billing.InvoiceLine
	(*Invoice)(nil),                // 5: billing.Invoice
	(*timestamppb.Timestamp)(nil),  // 6: google.protobuf.Timestamp
}
var file_billing_proto_depIdxs = []int32{
	6, // 0: billing.GenerateInvoiceRequest.billing_month:type_name -> google.protobuf.Timestamp
	5, // 1: billing.ListInvoicesResponse.invoices:type_name -> billing.Invoice
	6, // 2: billing.Invoice.billing_month:type_name -> google.protobuf.Timestamp
	4, // 3: billing.Invoice.lines:type_name -> billing.InvoiceLine
	6, // 4: billing.Invoice.created_at:type_name -> google.protobuf.Timestamp
	0, // 5: billing.BillingService.GenerateInvoice:input_type -> billing.GenerateInvoiceRequest
	1, // 6: billing.BillingService.GetInvoice:input_type -> billing.GetInvoiceRequest
	2, // 7: billing.BillingService.ListInvoices:input_type -> billing.ListInvoicesRequest
	5, // 8: billing.BillingService.GenerateInvoice:output_type -> billing.Invoice
	5, // 9: billing.BillingService.GetInvoice:output_type -> billing.Invoice
	3, // 10: billing.BillingService.ListInvoices:output_type -> billing.ListInvoicesResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_billing_proto_init() }
func file_billing_proto_init() {
	if File_billing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_billing_proto_rawDesc), len(file_billing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_billing_proto_goTypes,
		DependencyIndexes: file_billing_proto_depIdxs,
		MessageInfos:      file_billing_proto_msgTypes,
	}.Build()
	File_billing_proto = out.File
	file_billing_proto_goTypes = nil
	file_billing_proto_depIdxs = nil
}
