global:
  scrape_interval: 5s
scrape_configs:
  - job_name: 'tracker'
    static_configs:
      - targets: ['127.0.0.1:8081', '127.0.0.1:8082', '127.0.0.1:8083', '127.0.0.1:8084']
  - job_name: 'processor'
    static_configs:
      - targets: ['processor:8086']
