global:
  scrape_interval: 5s
scrape_configs:
  - job_name: 'tracker'
    static_configs:
      - targets: ['127.0.0.1:8181', '127.0.0.1:8182', '127.0.0.1:8183', '127.0.0.1:8184']
  - job_name: 'processor'
    static_configs:
      - targets: ['processor:8186']
